query, product_title, relevance_label

https://huggingface.co/docs/peft/v0.8.0/en/task_guides/semantic-similarity-lora

https://medium.com/@venkat.ramrao/fine-tuning-a-sentence-transformer-for-semantic-search-7c7a57f4db2f

https://medium.com/@kelvin.lu.au/fine-tuning-embedding-model-with-peft-and-lora-3b6f08987c24

# Import data

In [5]:
from pymongo import MongoClient
import pandas as pd

# MongoDB connection details
mongo_uri = "mongodb://localhost:27017/"
db_name = "task1"
collection_name = "bbc_news"

# Connect to MongoDB
client = MongoClient(mongo_uri)
db = client[db_name]
collection = db[collection_name]

documents = list(collection.find())
df = pd.DataFrame(documents)
client.close()

df.head()

,_id,title,pubDate,guid,link,description,content,openai_embedding
0,671e2d0aeccd4a5f4883e981,Justin Welby: Political leaders should treat o...,2024-01-01 00:00:04,https://www.bbc.co.uk/news/uk-67844356,https://www.bbc.co.uk/news/uk-67844356?at_medi...,The Archbishop of Canterbury urges politicians...,Justin Welby: Political leaders should treat o...,"[0.02301846444606781, -0.006470758933573961, 0..."
1,671e2d0aeccd4a5f4883e982,Almost three million tested for cancer in England,2024-01-01 00:09:56,https://www.bbc.co.uk/news/health-67841348,https://www.bbc.co.uk/news/health-67841348?at_...,Record numbers are being tested for cancer but...,Almost three million tested for cancer in Engl...,"[0.0134049067273736, 0.012411133386194706, 0.0..."
2,671e2d0aeccd4a5f4883e983,Household energy price rise of 5% comes into f...,2024-01-01 00:00:16,https://www.bbc.co.uk/news/business-67785266,https://www.bbc.co.uk/news/business-67785266?a...,A higher cap for the next three months adds £9...,Household energy price rise of 5% comes into f...,"[-0.00222824071533978, 0.032821644097566605, 0..."
3,671e2d0aeccd4a5f4883e984,Primrose Hill stabbing: Harry Pitman named as ...,2024-01-01 17:11:13,https://www.bbc.co.uk/news/uk-england-london-6...,https://www.bbc.co.uk/news/uk-england-london-6...,"Harry Pitman, 16, was attacked on London's Pri...",Primrose Hill stabbing: Harry Pitman named as ...,"[-0.0027212619315832853, 0.003952309023588896,..."
4,671e2d0aeccd4a5f4883e985,Israel Supreme Court strikes down judicial ref...,2024-01-01 19:47:58,https://www.bbc.co.uk/news/world-middle-east-6...,https://www.bbc.co.uk/news/world-middle-east-6...,The controversial plans triggered nationwide p...,Israel Supreme Court strikes down judicial ref...,"[0.026911897584795952, 0.025074539706110954, 0..."

Save the content to csv to let ChatGPT create the queries

In [4]:
df['content'].to_csv('notebooks_data/news_content.csv', index=False)

## Query data

Queries created by ChatGPT

In [11]:
gpt_queries = pd.read_csv('notebooks_data/user_queries.csv')
gpt_queries

                                             user_query
0                What is the latest update on politics?
1     Can you explain the recent developments in pol...
2              How has politics changed in recent news?
3          What is the current situation with politics?
4     What are the key takeaways from the recent new...
...                                                 ...
4995  What are the benefits of the recent changes in...
4996  Could you summarize the controversy around edu...
4997  Could you provide an overview of the recent ev...
4998  What are the key takeaways from the recent new...
4999  What impact does the politics have on daily life?

[5000 rows x 1 columns]

In [12]:
gpt_queries['user_query'].duplicated().sum()

np.int64(4692)

In [15]:
unique_gpt_queries = gpt_queries.drop_duplicates(subset='user_query')
print(len(unique_gpt_queries))
print(unique_gpt_queries['user_query'].duplicated().sum())

308
0

In [16]:
unique_gpt_queries.to_csv('notebooks_data/user_queries_unique.csv', index=False)

### Using ChatGPT to create 2K content query examples

Create 2K random news content dataset

In [25]:
random_news = df.sample(n=5).reset_index(drop=True)
for index, content in random_news['content'].items():
    print(f'"{content}"')

"Scotland fans endure humbling Euro  opener against Germany. The hosts defeated Steve Clarke's men 5-1 in the opening match of the tournament in Munich."
"Explosions hit Odesa as Zelensky meets Greek PM. Ukraine's navy says five people have been killed after missile strikes in the southern port city."
"Smith beats Littler and Price on way to opening Premier League win. Michael Smith beats Gerwyn Price to win the opening night of the 2024 Premier League Darts in Cardiff."
"Israel officials support Gaza destruction, court hears. South African lawyers present their case on the first day of a hearing at the UN's top court."
"Police investigate 'care of dead' at funeral homes. An investigation begins after "a report received of concern for care of the deceased"."

In [22]:
"""
RSS news content:
<news>"Scotland fans endure humbling Euro opener against Germany. The hosts defeated Steve Clarke's men 5-1 in the opening match of the tournament in Munich."</news>
<query1>"How did Scotland perform in their Euro opener against Germany?"</query1>
<query2>"What challenges is Scotland facing in the current Euro tournament?"</query2>
<news>"Explosions hit Odesa as Zelensky meets Greek PM. Ukraine's navy says five people have been killed after missile strikes in the southern port city."</news>
<query1>"What were the casualties from the recent missile strikes in Odesa?"</query1>
<query2>"How is Ukraine handling the conflict in its southern port cities?"</query2>
<news>"Israel officials support Gaza destruction, court hears. South African lawyers present their case on the first day of a hearing at the UN's top court."</news>
<query1>"What did Israel officials testify regarding Gaza at the UN court hearing?"</query1>
<query2>"What legal actions are being taken internationally concerning Gaza?"</query2>
<news>"Smith beats Littler and Price on way to opening Premier League win. Michael Smith beats Gerwyn Price to win the opening night of the 2024 Premier League Darts in Cardiff."</news>
<query1>"Who won the opening night of the 2024 Premier League Darts?"</query1>
<query2>"How has Michael Smith's performance been in recent darts tournaments?"</query2>
<news>"'Positives for Liverpool - but a big chance missed'. MOTD2 pundit Danny Murphy says Liverpool's draw at Old Trafford is not the end of the world for their title hopes - but they should have secured all three points."</news>
<query1>"What were Danny Murphy's comments on Liverpool's draw at Old Trafford?"</query1>
<query2>"What are the implications of Liverpool's recent performances for their title hopes?"</query2>
"""

'\nRSS news content:\n<news>"Steve Rosenberg on Russia\'s stage-managed election. In Borovsk, Steve Rosenberg looks at the Russia Putin wants you to see - and Russia in reality."</news>\n"Serving Met Police officer in court charged with rape. The Met says the case relates to a report a man was raped at a home in north London last Monday."\n"Who will replace McConnell as top Senate Republican?. The three "Johns" and a senator who challenged Mr McConnell for his post are considered likely successors."\n"King\'s official Coronation scroll is first without animal skin. For 700 years there has been a handwritten account of coronations, but there are some names missing."\n"\'Positives for Liverpool - but a big chance missed\'. MOTD2 pundit Danny Murphy says Liverpool\'s draw at Old Trafford is not the end of the world for their title hopes - but they should have secured all three points."\n'

In [37]:
random_news = df.sample(n=5).reset_index(drop=True)
for index, content in random_news['content'].items():
    print(f'"{content}"')

"North Sea oil and gas claims fact-checked. The government wants to guarantee annual oil and gas licensing rounds to "improve energy security"."
"Pupils injured in crush at school gate. The head teacher says a "surge" developed when the gate was not opened at the end of the school day."
"Sixth person charged with spying for Russia in UK. Bulgarian national Tihomir Ivanov Ivanchev, 38, will appear in court on Wednesday."
"'We went viral as Oompa Loompas but we're just normal people'. Kirsty Paterson and Jenny Fogarty were hired to work at the Willy Wonka Chocolate Experience in Glasgow."
"BBC Proms conductor Sir Andrew Davis dies aged 80. Sir Andrew was one of the longest-serving chief conductors of the BBC Symphony Orchestra."

In [31]:
from openai import OpenAI

client = OpenAI(api_key='<API_KEY>')
def ask_chatgpt_4o_mini(prompt: str) -> str:
    """
    Use the OpenAI ChatGPT-4o-mini to generate an answer based on the given prompt.

    Args:
        prompt (str): The prompt for the chatbot.

    Returns:
        str: The generated answer.
    """
    completion = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    return completion.choices[0].message.content.strip()

In [34]:
import re

def extract_queries(model_response):
    # Regular expressions to extract content within <query1> and <query2> tags
    query1_match = re.search(r'<query1>"(.*?)"</query1>', model_response)
    query2_match = re.search(r'<query2>"(.*?)"</query2>', model_response)
    
    # Extract the matched content if available
    query1 = query1_match.group(1) if query1_match else None
    query2 = query2_match.group(1) if query2_match else None
    
    return query1, query2

In [38]:
random_news = df.sample(n=1000).reset_index(drop=True)

In [40]:
import pandas as pd

# Initialize an empty list to gather results
results = []

# Loop through each row in the `random_news` DataFrame
for index, row in random_news.iterrows():
    news_content = row['content']
    
    # Create the prompt
    prompt = f"""
I have a dataset of news content, and I need to generate two user queries for each news article. The queries should be relevant to the news content and answerable based on it. 
Here is the format I need for each news article:

<news>"[NEWS_CONTENT]"</news>
<query1>"[QUERY_1]"</query1>
<query2>"[QUERY_2]"</query2>

Guidelines for creating queries:
1. Make the first query closely related to the specific details of the news.
2. Make the second query relevant to the main topic but broader, covering general aspects of the subject.

Please provide two queries in the exact format shown for each news article. Below are some examples to follow:

<news>"Scotland fans endure humbling Euro opener against Germany. The hosts defeated Steve Clarke's men 5-1 in the opening match of the tournament in Munich."</news>
<query1>"How did Scotland perform in their Euro opener against Germany?"</query1>
<query2>"How are going the Euro games?"</query2>
<news>"Explosions hit Odesa as Zelensky meets Greek PM. Ukraine's navy says five people have been killed after missile strikes in the southern port city."</news>
<query1>"What were the casualties from the recent missile strikes in Odesa?"</query1>
<query2>"Ukraine casualties in the war?"</query2>

Now, for this news content:

<news>"{news_content}"</news>

Generate:
<query1>"</query1>
<query2>"</query2>
"""
    
    # Call the function to get the model's response
    model_response = ask_chatgpt_4o_mini(prompt)
    
    # Extract queries from the model's response
    query1, query2 = extract_queries(model_response)
    
    # Append each query as a separate row in results
    if query1:
        results.append({'query': query1, 'news_content': news_content})
    if query2:
        results.append({'query': query2, 'news_content': news_content})
    
    # Print the progress
    if (index + 1) % 10 == 0:  # Adjust the modulus value to print more or less frequently
        percent_complete = ((index + 1) / len(random_news)) * 100
        print(f"Processed {percent_complete:.0f}% -> {index + 1} out of {len(random_news)} rows.")

# Convert the list of results to a DataFrame
queries_df = pd.DataFrame(results)

# Save the DataFrame to a CSV file
queries_df.to_csv('notebooks_data/generated_queries.csv', index=False)

print("Query generation and saving to CSV completed.")

Processed 1% -> 10 out of 1000 rows.
Processed 2% -> 20 out of 1000 rows.
Processed 3% -> 30 out of 1000 rows.
Processed 4% -> 40 out of 1000 rows.
Processed 5% -> 50 out of 1000 rows.
Processed 6% -> 60 out of 1000 rows.
Processed 7% -> 70 out of 1000 rows.
Processed 8% -> 80 out of 1000 rows.
Processed 9% -> 90 out of 1000 rows.
Processed 10% -> 100 out of 1000 rows.
Processed 11% -> 110 out of 1000 rows.
Processed 12% -> 120 out of 1000 rows.
Processed 13% -> 130 out of 1000 rows.
Processed 14% -> 140 out of 1000 rows.
Processed 15% -> 150 out of 1000 rows.
Processed 16% -> 160 out of 1000 rows.
Processed 17% -> 170 out of 1000 rows.
Processed 18% -> 180 out of 1000 rows.
Processed 19% -> 190 out of 1000 rows.
Processed 20% -> 200 out of 1000 rows.
Processed 21% -> 210 out of 1000 rows.
Processed 22% -> 220 out of 1000 rows.
Processed 23% -> 230 out of 1000 rows.
Processed 24% -> 240 out of 1000 rows.
Processed 25% -> 250 out of 1000 rows.
Processed 26% -> 260 out of 1000 rows.
Processed 27% -> 270 out of 1000 rows.
Processed 28% -> 280 out of 1000 rows.
Processed 29% -> 290 out of 1000 rows.
Processed 30% -> 300 out of 1000 rows.
Processed 31% -> 310 out of 1000 rows.
Processed 32% -> 320 out of 1000 rows.
Processed 33% -> 330 out of 1000 rows.
Processed 34% -> 340 out of 1000 rows.
Processed 35% -> 350 out of 1000 rows.
Processed 36% -> 360 out of 1000 rows.
Processed 37% -> 370 out of 1000 rows.
Processed 38% -> 380 out of 1000 rows.
Processed 39% -> 390 out of 1000 rows.
Processed 40% -> 400 out of 1000 rows.
Processed 41% -> 410 out of 1000 rows.
Processed 42% -> 420 out of 1000 rows.
Processed 43% -> 430 out of 1000 rows.
Processed 44% -> 440 out of 1000 rows.
Processed 45% -> 450 out of 1000 rows.
Processed 46% -> 460 out of 1000 rows.
Processed 47% -> 470 out of 1000 rows.
Processed 48% -> 480 out of 1000 rows.
Processed 49% -> 490 out of 1000 rows.
Processed 50% -> 500 out of 1000 rows.
Processed 51% -> 510 out of 1000 rows.
Processed 52% -> 520 out of 1000 rows.
Processed 53% -> 530 out of 1000 rows.
Processed 54% -> 540 out of 1000 rows.
Processed 55% -> 550 out of 1000 rows.
Processed 56% -> 560 out of 1000 rows.
Processed 57% -> 570 out of 1000 rows.
Processed 58% -> 580 out of 1000 rows.
Processed 59% -> 590 out of 1000 rows.
Processed 60% -> 600 out of 1000 rows.
Processed 61% -> 610 out of 1000 rows.
Processed 62% -> 620 out of 1000 rows.
Processed 63% -> 630 out of 1000 rows.
Processed 64% -> 640 out of 1000 rows.
Processed 65% -> 650 out of 1000 rows.
Processed 66% -> 660 out of 1000 rows.
Processed 67% -> 670 out of 1000 rows.
Processed 68% -> 680 out of 1000 rows.
Processed 69% -> 690 out of 1000 rows.
Processed 70% -> 700 out of 1000 rows.
Processed 71% -> 710 out of 1000 rows.
Processed 72% -> 720 out of 1000 rows.
Processed 73% -> 730 out of 1000 rows.
Processed 74% -> 740 out of 1000 rows.
Processed 75% -> 750 out of 1000 rows.
Processed 76% -> 760 out of 1000 rows.
Processed 77% -> 770 out of 1000 rows.
Processed 78% -> 780 out of 1000 rows.
Processed 79% -> 790 out of 1000 rows.
Processed 80% -> 800 out of 1000 rows.
Processed 81% -> 810 out of 1000 rows.
Processed 82% -> 820 out of 1000 rows.
Processed 83% -> 830 out of 1000 rows.
Processed 84% -> 840 out of 1000 rows.
Processed 85% -> 850 out of 1000 rows.
Processed 86% -> 860 out of 1000 rows.
Processed 87% -> 870 out of 1000 rows.
Processed 88% -> 880 out of 1000 rows.
Processed 89% -> 890 out of 1000 rows.
Processed 90% -> 900 out of 1000 rows.
Processed 91% -> 910 out of 1000 rows.
Processed 92% -> 920 out of 1000 rows.
Processed 93% -> 930 out of 1000 rows.
Processed 94% -> 940 out of 1000 rows.
Processed 95% -> 950 out of 1000 rows.
Processed 96% -> 960 out of 1000 rows.
Processed 97% -> 970 out of 1000 rows.
Processed 98% -> 980 out of 1000 rows.
Processed 99% -> 990 out of 1000 rows.
Processed 100% -> 1000 out of 1000 rows.
Query generation and saving to CSV completed.

# Fine tuning E5

In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split

queries_df = pd.read_csv('notebooks_data/generated_queries.csv')
train_df, test_df = train_test_split(queries_df, test_size=0.3, random_state=42)
print(f"Training set size: {len(train_df)}")
print(f"Test set size: {len(test_df)}")

Training set size: 1399
Test set size: 600

## Load the Model and Tokenizer with 8-Bit Quantization

In [7]:
from transformers import AutoTokenizer, AutoModel
from peft import LoraConfig, get_peft_model

# Load tokenizer and model without quantization
model_name = "intfloat/e5-large-v2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)  # Standard loading, no quantization

## Configure QLoRA

In [8]:
# Define QLoRA configuration
lora_config = LoraConfig(
    r=8,               # Rank of the low-rank matrices
    lora_alpha=8,      # Scaling factor for LoRA updates
    target_modules=["key", "query", "value"],  # Adjust based on model structure if necessary
    lora_dropout=0.1,   # Dropout for LoRA layers
    bias="none"         # Exclude biases to focus on core layers
)

# Wrap the model with QLoRA
model = get_peft_model(model, lora_config)

## Pre-Fine-Tuning Performance Evaluation

In [9]:
import torch

def get_embeddings(text, model, tokenizer):
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True).to("cpu")
    with torch.no_grad():
        embeddings = model(**inputs).last_hidden_state.mean(dim=1).cpu().numpy()
    return embeddings


df['e5_embedding_before_tuning'] = df['content'].apply(lambda x: get_embeddings(x, model, tokenizer))

In [10]:
from sklearn.metrics.pairwise import cosine_similarity

def find_top_news(query, df, model, tokenizer, top_k=10):
    query_embedding = get_embeddings(query, model, tokenizer)

    # Calculate cosine similarity between query and all news embeddings
    similarities = df['e5_embedding_before_tuning'].apply(lambda x: cosine_similarity(query_embedding, x)[0][0])
    
    # Add similarity scores to the DataFrame
    df['e5_similarity'] = similarities
    
    # Sort by similarity and return the top_k results
    top_matches = df.nlargest(top_k, 'e5_similarity')
    
    # Clean up by dropping the 'similarity' column
    df.drop(columns=['e5_similarity'], inplace=True)
    
    return top_matches[['content', 'e5_similarity']]

test_queries = ["Products for Color-blind people","JEEP off-road vehicles","What is the origin of Bamba snack","Recommended diet and exercise habits for managing obesity","Keep your children safe on the internet","What are the lates news about AI ethics?","How the war between Israel and Hamas is affecting global politics?","Latest trends in the fashion industry","Interest rates","biden vs trump","Best Marvel movie this year","Northern Lights"]
for user_query in test_queries:
    print(f"\n\nQuery: {user_query}")
    top_news = find_top_news(user_query, df, model, tokenizer)
    for _, row in top_news.iterrows():
                print(f"\033[96m Similarity: {row['e5_similarity']:.3f}::\033[0m {row['content']}")

Query: Products for Color-blind people
 Similarity: 0.785:: Cost of living: How can I make extra income?. Some people have been earning thousands selling clothes and other items since they were in school.
 Similarity: 0.780:: Ethnic bias in health devices 'puts patients at risk'. The review focuses on devices frequently used in the NHS, like pulse oximeters and skin cancer apps.
 Similarity: 0.774:: Americanswers! What is Project 2025? Will Biden take a cognitive test?. We answer your questions on the biggest issues in the run-up to the election
 Similarity: 0.774:: Electioncast: Laura Kuenssberg and Adam Fleming answer your questions. Adam and Laura answer your election questions
 Similarity: 0.773:: The List. Exploring 9 amazing space missions.
 Similarity: 0.773:: Who can I vote for in the general election?. Find out which constituency you are in, who you can vote for and where you can vote using our postcode search.
 Similarity: 0.773:: 'I’ve invented an alternative to uncomfortable smear tests'. Sânziana Foia's non-invasive test detects harmful virus strains and delivers fast results at home.
 Similarity: 0.772:: Cost of living payments: What are they and who gets them?. Millions of low-income households will receive a final cost of living payment soon.
 Similarity: 0.772:: Aphantasia: Why I cannot see my children in my mind. Not everyone can picture images in their mind's eye and remember sounds or faces - but why?
 Similarity: 0.770:: Musician with hearing loss makes music from nature. A musician who lost her hearing overnight says it spurred her on to make new music from nature.


Query: JEEP off-road vehicles
 Similarity: 0.765:: How to drive in icy weather. Tips on what to carry in your car, and how to drive in snow and icy weather.
 Similarity: 0.740:: Watch: Wheelie bins fly and a caravan overturns in wind. Cars are damaged and houses shake as a suspected tornado strikes in Knutton, Staffordshire.
 Similarity: 0.740:: Our Range Rovers are not UK's most-stolen car, says Jaguar Land Rover. The boss of Jaguar Land Rover hits out at what he says is inaccurate reporting about the Range Rover.
 Similarity: 0.740:: Collapsing cliffs and washed-out roads after California storms. Days of heavy rainfall in California have caused flooding and mudslides, leaving infrastructure damaged.
 Similarity: 0.740:: Adults and teens turn to 'dumbphones'  to cut screen time. Parents and teens alike are trading in their smartphones for "dumber" models to help stay offline.
 Similarity: 0.739:: TV star shaken after Jaguar brakes fail during drive. Craig Phillips describes "terrifying feeling" when brakes failed on his Jaguar I-Pace
 Similarity: 0.736:: UAE: A hailstorm in the desert? Rare weather phenomenon shocks residents. Large hailstones covered roads as a rare weather phenomenon hit the United Arab Emirates.
 Similarity: 0.736:: California: Rockslide blocking road cleared with explosives. Video shared by Placer County shows a road completely blocked by boulders, that are then blasted into small pieces.
 Similarity: 0.735:: Have the wheels come off for Tesla?. As the electric carmaker sees sales fall and cuts jobs, we take a closer look at its problems.
 Similarity: 0.733:: Walkers forced to trespass onto open access countryside. Right to roam campaigners say hundreds of "open country" locations are inaccessible to the public.


Query: What is the origin of Bamba snack
 Similarity: 0.756:: The Birmingham child who paved the way for the heel prick test. Sheila Jones, who had Phenylketonuria (PKU), was treated by pioneering doctors 70 years ago.
 Similarity: 0.756:: Big Zuu cuts down on cooking and rap for Ramadan. The rapper and TV chef visited Mecca for the first time to explore his Muslim faith for a documentary.
 Similarity: 0.755:: Nigeria's love-hate relationship with twins. Two communities with different views about twins that meant the difference between life and death.
 Similarity: 0.755:: Kamila Valieva claimed contaminated strawberry dessert behind positive test. Banned figure skater Kamila Valieva claimed her positive doping test may have been caused by a contaminated strawberry dessert.
 Similarity: 0.754:: Scientists grow 'meaty' rice hybrid food for protein kick. A team in South Korea say they have cracked how to grow beef muscle and fat cells inside grains of rice.
 Similarity: 0.752:: Come Dine With Me winners part of drug import plot. Members of a gang to import cannabis were foiled after reports of a theft, police say.
 Similarity: 0.752:: One Love: How Kingsley Ben-Adir became Bob Marley on the set of Barbie. The actor initially turned down the role, saying it was too risky. What changed his mind?
 Similarity: 0.752:: Raisin found in toddler's nose after three-month mystery. Three-year-old Peyton Handley told her parents that she had a pain and would scratch around her nose.
 Similarity: 0.752:: The real story behind Bohemian Rhapsody. The full story behind Queen's iconic song.
 Similarity: 0.751:: Squirrels may have given medieval Britons leprosy. It’s the first time a medieval animal has been identified as a host for the disease.


Query: Recommended diet and exercise habits for managing obesity
 Similarity: 0.827:: Weighing up diet drugs. Obesity jabs 'could reduce heart attack risk' says new study
 Similarity: 0.797:: How do I register to vote?. Here’s what you need to know about how you register to vote and when.
 Similarity: 0.794:: Are we being tricked by our fitness trackers?. How accurate are fitness trackers?
 Similarity: 0.790:: Post Christmas debt: Which bills should I pay first?. What help and options are available to people struggling with debt repayments?
 Similarity: 0.788:: How to drive in icy weather. Tips on what to carry in your car, and how to drive in snow and icy weather.
 Similarity: 0.785:: What can I do if I can't pay my energy bill?. If you're struggling to afford your gas and electricity bills, what options are available?
 Similarity: 0.784:: How to win an Oscar. The campaigning behind the Academy Awards
 Similarity: 0.781:: Dog attacks: What can you do to protect yourself?. The best course of action will vary depending on the situation, dog behaviour experts explain.
 Similarity: 0.781:: Everything you need to know about student loans. How do they work across the UK, what can I borrow and when do I have to start paying it back?
 Similarity: 0.781:: Who can I vote for in the general election?. Find out which constituency you are in, who you can vote for and where you can vote using our postcode search.


Query: Keep your children safe on the internet
 Similarity: 0.820:: Tame toxic algorithms to protect children, big tech told. Big tech companies will have to make changes to their algorithms to comply with new online safety laws.
 Similarity: 0.816:: Brianna Ghey's mother and Molly Russell's father join forces to combat online harm. Esther Ghey and Ian Russell want better protection for teenagers on social media.
 Similarity: 0.815:: Bereaved parents win online harm battle. Tech firms will have to hand over personal data of children whose death may be related to online harm.
 Similarity: 0.806:: Tech firms told to hide 'toxic' content from children. Social media firms like Instagram and TikTok will have to make changes to comply with new online safety laws.
 Similarity: 0.800:: Back-to-school illness advice offered to parents. Health officials explain when to keep your child at home and how to stop the spread of bugs.
 Similarity: 0.798:: Rochdale abuse scandal: Inside the team fighting child sexual exploitation. How are police and child protection experts trying to prevent a repeat of the Rochdale abuse scandal?
 Similarity: 0.795:: Meta tool to block nude images in teens' private messages. The move is designed to help stop teenagers receiving inappropriate pictures, even in encrypted chats
 Similarity: 0.791:: Police investigate virtual sex assault on girl's avatar. The incident in a virtual world reportedly left the under-16-year-old traumatised.
 Similarity: 0.791:: New law aims to protect devices from hackers. Speakers, fitness trackers and other internet-connected devices sold in the UK now have to meet new requirements.
 Similarity: 0.788:: Pupils get rare alert over dangers of sextortion. The National Crime Agency says young boys are increasingly being targeted by gangs.


Query: What are the lates news about AI ethics?
 Similarity: 0.806:: AI and humanity’s future: chilling or thrilling?. Amol & Nick take on Stephen Fry’s challenge & look at what the future of AI might entail.
 Similarity: 0.805:: Concern rises over AI in adult entertainment. AI in adult entertainment could have negative effects on society and individuals, experts say.
 Similarity: 0.804:: How AI is being used to prevent illegal fishing. Illegal fishing remains a huge global problem, but AI is now being used to tackle the issue.
 Similarity: 0.804:: CES 2024: AI pillows and toothbrushes - is it all getting a bit silly?. Companies are clamouring to present their products as AI-powered, but are their claims justified?
 Similarity: 0.803:: New version of Chat-GPT can teach maths and flirt . OpenAI has unveiled a new, faster version of its generative AI tool, ChatGPT.
 Similarity: 0.801:: How AI is helping to prevent future power cuts. Artificial intelligence software is being used to predict electricity demand and supply.
 Similarity: 0.799:: AI could 'supercharge' election disinformation, US tells the BBC. US Deputy Attorney General Lisa Monaco says the US wants tougher sentences for crimes involving AI.
 Similarity: 0.799:: Urgent need for terrorism AI laws, warns think tank. The government should 'urgently consider' AI-specific legislation a think-tank says.
 Similarity: 0.798:: AI will not be the destroyer of jobs - Bank chief. Bank of England governor says AI has "great potential" as Lords report urges UK to embrace AI.
 Similarity: 0.795:: AI photos show people with cancer their lost future. People with secondary breast cancer view photos of themselves at events they may not live to see.


Query: How the war between Israel and Hamas is affecting global politics?
 Similarity: 0.840:: Israel-Palestinian bitterness deepened by Hamas attack and war. Both Israelis and Palestinians believe the world does not understand their pain and suffering.
 Similarity: 0.836:: Chris Mason: How Gaza conflict is contorting UK politics. The Conservatives, Labour, and Parliament itself are finding themselves torn by the furious arguments provoked by the Israel-Gaza war.
 Similarity: 0.831:: Could the Israel-Gaza war cost Biden the election?. The President’s said he’s 'outraged' by aid worker killings
 Similarity: 0.829:: Jeremy Bowen: What ICC arrest warrants mean for Israel and Hamas. The Israeli and Hamas leaders are suspected of committing war crimes during the continuing war in Gaza.
 Similarity: 0.820:: Why have Israel and Iran attacked each other?. The long-running shadow war between the two countries has come into the open.
 Similarity: 0.819:: Jeremy Bowen: Obstacles to peace seem larger than ever. The risk of an all-out Middle East war is increasing as the crisis in Gaza grows ever more desperate.
 Similarity: 0.819:: No let-up for Gazans while world focused on Iran attacks. Fighting continues in Gaza, where a humanitarian crisis is overshadowed by the wider regional conflict.
 Similarity: 0.818:: Lyse Doucet: Hamas leader's assassination sparks wider war fears. Lyse Doucet assesses if Hezbollah and Hamas will retaliate after Saleh al-Arouri was killed in Lebanon.
 Similarity: 0.818:: Have Iran-Israel missile strikes changed the Middle East?. Political and military leaders are still absorbing the extraordinary exchange of fire, writes James Landale.
 Similarity: 0.818:: Israel-Gaza war: Latest ceasefire talks not very promising - Qatar. Israel's PM Benjamin Netanyahu vows to carry on the war against Hamas regardless of international pressure.


Query: Latest trends in the fashion industry
 Similarity: 0.806:: How Zendaya perfected 'method dressing'. Film stars have made fancy dress fashionable in their recent red carpet looks.
 Similarity: 0.792:: Champagne, caffeine and chaos: Fashion week descends on Paris. Louis Vuitton, Dior, Hermes, Rick Owens, Loewe, Kenzo and Dries Van Noten all introduce new collections in Paris.
 Similarity: 0.790:: Egg Freezing and Me. Inside the world of one of the fastest growing fertility treatments in the UK.
 Similarity: 0.786:: The new language changing the dating scene. If you WLTM a ND with a GSOH, you might struggle to locate one on a modern dating app.
 Similarity: 0.785:: Kuenssberg: Are the politics of climate change going out of fashion?. Debate is shifting to cost concerns as net zero targets fast approach, says Laura Kuenssberg.
 Similarity: 0.781:: Cambodia: Fast fashion helps fuel blazing kilns where workers faint from heat. How hot is too hot to work? The BBC visits Cambodia's sweltering brick kilns to find out.
 Similarity: 0.780:: Stars take over Paris for sporty Vogue fashion show. Supermodels, singers and sports star took to the runway in Paris as Vogue turned a square into a runway.
 Similarity: 0.780:: Robot Ships. The revolution in shipping using 'ghost' vessels with hardly any crew on board.
 Similarity: 0.780:: The most eye-catching looks from the Met Gala so far. Lea Michelle, Zendaya and Gigi Hadid are among the stars walking the red carpet.
 Similarity: 0.780:: Zendaya and Kim Kardashian stun on Met Gala red carpet. The celebrities are showing up for fashion's night of nights in New York City.


Query: Interest rates
 Similarity: 0.837:: What are UK interest rates and when will they fall?. Bank of England interest rates affect the mortgage, loan and savings rates for millions of people.
 Similarity: 0.836:: Interest rates expected to be held at 5.25%. Despite inflation falling to 2%, experts are expecting interest rates to be held at a 16-year high.
 Similarity: 0.834:: How do interest rates affect me?. Bank of England interest rates have an impact on the mortgage, loan and savings rates for millions of people.
 Similarity: 0.832:: When will UK interest rates come down?. Bank of England interest rates affect mortgage, loan and savings rates for millions of people.
 Similarity: 0.832:: Inflation and Covid set our savings back 10 years. Justin Williams is one of many whose savings have eroded and mortgage rates have increased.
 Similarity: 0.825:: Mortgage lenders rapidly changing interest rates. HSBC, NatWest and Virgin Money are all increasing mortgage rates continuing a frantic start to the year.
 Similarity: 0.825:: Bank of England expected to hold interest rates. The Bank is widely expected to keep rates at 5.25% for now, but cut them later in the year.
 Similarity: 0.824:: Interest rate cuts 'on the way', says Bank boss. The Bank of England has kept the cost of borrowing at 5.25% for the fifth time in a row.
 Similarity: 0.820:: Interest rates won't fall due to 4% inflation, says Bank boss. Bank of England boss says the latest inflation figure "pretty much leaves us where we were".
 Similarity: 0.819:: Bank 'optimistic' as it edges closer to summer cut. Its comments came as UK interest rates were left unchanged at a 16-year high of 5.25%.


Query: biden vs trump
 Similarity: 0.856:: Super Tuesday: Everything Points to Trump vs Biden. Trump and Biden win almost every state in election season's biggest primary night.
 Similarity: 0.852:: Where Biden and Trump stand on key issues. How the two candidates' policies compare on the economy, immigration, abortion and other big issues.
 Similarity: 0.850:: Illegal migration, tax and abortion - fact checking Trump-Biden debate. BBC Verify looks into various claims made on stage by Donald Trump and Joe Biden.
 Similarity: 0.847:: Watch key moments from Biden and Trump's first debate. The pair threw insults and clashed on stage about the biggest issues American voters care about - here's what they said.
 Similarity: 0.847:: What to watch for at Biden and Trump's first debate. The BBC's Sarah Smith looks at what's at stake for both men as they prove they're worth a second White House term.
 Similarity: 0.845:: Biden faces high-stakes address to calm Democratic nerves. The president will seek to fight concerns over his age and contrast his term in office with Donald Trump's.
 Similarity: 0.843:: Big stakes and high tension as Biden-Trump debate looms. Thursday's debate between the two will be a reunion of sorts - although not exactly a friendly one.
 Similarity: 0.843:: Biden and Trump make competing trips to US border. The two likely presidential candidates make speeches in an effort to show they can tackle illegal crossings.
 Similarity: 0.836:: 'A reality show': World reacts to Trump-Biden debate . Global reviews were most scathing of Mr Biden, but his Republican challenger did not escape criticism.
 Similarity: 0.836:: Biden and Trump agree two debates as RFK cries foul. There will be no live audience at June's Atlanta event, which will mark the pair's first on-stage clash in four years.


Query: Best Marvel movie this year
 Similarity: 0.791:: Marvel star Jeremy Renner: I'm so blessed a year after accident. The Marvel star reflects on his recovery after being run over by his own snow plough last New Year's Day.
 Similarity: 0.773:: Tom Holland's Romeo wows crowds more than critics. Reviews describe the Spider-Man star's performance on stage as "good", "fine" and "perfectly OK".
 Similarity: 0.772:: Oscars 2024: Poor Things and Anatomy of a Fall scoop early awards. Best picture favourite Oppenheimer has 13 nominations and could become one of the biggest winners of all time.
 Similarity: 0.771:: Marvel star Karen Gillan is not scared of being cancelled . Scots actress Karen Gillan's new role made her face up to the pitfalls of social media.
 Similarity: 0.770:: Oppenheimer's Cillian Murphy and Robert Downey Jr scoop Bafta Film Awards. Cillian Murphy, Robert Downey Jr and Christopher Nolan all win Bafta Film Awards for Oppenheimer.
 Similarity: 0.768:: Oscars 2024: Everything you need to know ahead of big night of awards. As Hollywood's finest get ready for the big night, we bring you the lowdown on what to look out for.
 Similarity: 0.767:: The full list of Oscar winners - updating live. See who has won and been nominated for this year's coveted Academy Awards.
 Similarity: 0.767:: Bafta nominations 2024: The full list of film contenders. Oppenheimer and Poor Things are the leading contenders for this year's British Academy Film Awards.
 Similarity: 0.765:: 'The Valhalla nail-biter that had everything'. Xander Schauffele’s thrilling breakthrough PGA victory over Bryson DeChambeau portrayed major golf in the best possible light, writes Iain Carter.
 Similarity: 0.765:: The highs, lows and why Swift won. The best (and worst) performances, the memorable moments, and why Swift's big win was inevitable.


Query: Northern Lights
 Similarity: 0.853:: Why you probably missed the Northern Lights on Saturday. The Northern Lights waned early on Saturday night, but picked up again much later.
 Similarity: 0.851:: More Northern Lights soon as Sun storms strengthen. Another spectacular light show could come within two weeks as Sun storms reach 11-year high.
 Similarity: 0.850:: In pictures: Northern Lights dazzle around the world. The aurora borealis was visible around the world on Friday night, stunning photographers everywhere.
 Similarity: 0.848:: Northern lights give spectacular surprise display across UK. In a sudden display the aurora was seen from the Highlands down to Cornwall on Sunday night.
 Similarity: 0.846:: Watch: Northern Lights captured glowing over volcano. Volcanic eruptions have been taking place in the region since 14 January.
 Similarity: 0.840:: Northern Lights in dazzling display across the UK. A solar storm of this scale can cause disruptions to infrastructure such as the power grid.

In [11]:
import torch
from sklearn.metrics.pairwise import cosine_similarity

# Helper function to get embeddings
def get_embeddings(text, model, tokenizer):
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True).to("cpu")
    with torch.no_grad():
        embeddings = model(**inputs).last_hidden_state.mean(dim=1).cpu().numpy()
    return embeddings

# Calculate pre-fine-tuning similarities
similarities_before = []
for index, row in test_df.iterrows():
    query_embedding = get_embeddings(row['query'], model, tokenizer)
    content_embedding = get_embeddings(row['news_content'], model, tokenizer)
    similarity = cosine_similarity(query_embedding, content_embedding)[0][0]
    similarities_before.append(similarity)

    # Print the progress
    if (index + 1) % 100 == 0:  # Adjust the modulus value to print more or less frequently
        percent_complete = ((index + 1) / len(test_df)) * 100
        print(f"Processed {percent_complete:.0f}% -> {index + 1} out of {len(test_df)} rows.")

# Store pre-fine-tuning similarities
test_df['similarity_before'] = similarities_before
test_df.to_csv('notebooks_data/generated_queries_with_similarity_before.csv', index=False)
print("Average Pre-Fine-Tuning Similarity:", sum(similarities_before) / len(similarities_before))

Processed 300% -> 1800 out of 600 rows.
Processed 17% -> 100 out of 600 rows.
Processed 100% -> 600 out of 600 rows.
Processed 267% -> 1600 out of 600 rows.
Processed 33% -> 200 out of 600 rows.
Processed 217% -> 1300 out of 600 rows.
Processed 233% -> 1400 out of 600 rows.
Average Pre-Fine-Tuning Similarity: 0.8459771

## Prepare Data for Fine-Tuning
Define a dataset class to tokenize query and news_content for the model.

In [12]:
from torch.utils.data import Dataset, DataLoader

class QueryNewsDataset(Dataset):
    def __init__(self, df, tokenizer, max_length=128):
        self.queries = df['query'].tolist()
        self.news = df['news_content'].tolist()
        self.tokenizer = tokenizer
        self.max_length = max_length
    
    def __len__(self):
        return len(self.queries)
    
    def __getitem__(self, idx):
        query_text = self.queries[idx]
        news_text = self.news[idx]
        
        query_inputs = self.tokenizer(query_text, padding='max_length', truncation=True, max_length=self.max_length, return_tensors="pt")
        news_inputs = self.tokenizer(news_text, padding='max_length', truncation=True, max_length=self.max_length, return_tensors="pt")
        
        return {
            'query_input_ids': query_inputs['input_ids'].squeeze(0),
            'query_attention_mask': query_inputs['attention_mask'].squeeze(0),
            'news_input_ids': news_inputs['input_ids'].squeeze(0),
            'news_attention_mask': news_inputs['attention_mask'].squeeze(0)
        }

# Create DataLoader for fine-tuning
train_loader = DataLoader(QueryNewsDataset(test_df, tokenizer), batch_size=8, shuffle=True)

## Fine-Tune the Model with QLoRA

Define a cosine similarity loss and run the fine-tuning loop.

In [13]:
import torch
from torch.nn import functional as F
from transformers import AdamW

# Optimizer
optimizer = AdamW(model.parameters(), lr=2e-5)

# Custom similarity loss function
def similarity_loss(embedding1, embedding2):
    cos_sim = F.cosine_similarity(embedding1, embedding2)
    return 1 - cos_sim.mean()

# Fine-tuning loop with progress updates
model.train()
for epoch in range(3):  # Adjust the number of epochs as needed
    total_loss = 0
    for i, batch in enumerate(train_loader):
        optimizer.zero_grad()
        
        # Query embeddings
        query_embeddings = model(
            input_ids=batch['query_input_ids'],
            attention_mask=batch['query_attention_mask']
        ).last_hidden_state.mean(dim=1)
        
        # News content embeddings
        news_embeddings = model(
            input_ids=batch['news_input_ids'],
            attention_mask=batch['news_attention_mask']
        ).last_hidden_state.mean(dim=1)
        
        # Calculate similarity loss and optimize
        loss = similarity_loss(query_embeddings, news_embeddings)
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
        
        # Print progress within each epoch
        if (i + 1) % 10 == 0:
            percent_complete = ((i + 1) / len(train_loader)) * 100
            print(f"Epoch {epoch + 1} - Processed {percent_complete:.0f}% -> {i + 1} out of {len(train_loader)} batches.")

    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch + 1} completed with average loss: {avg_loss:.4f}")

/Users/who/projects/task1/venv/lib/python3.11/site-packages/transformers/optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(

Epoch 1 - Processed 13% -> 10 out of 75 batches.
Epoch 1 - Processed 27% -> 20 out of 75 batches.
Epoch 1 - Processed 40% -> 30 out of 75 batches.
Epoch 1 - Processed 53% -> 40 out of 75 batches.
Epoch 1 - Processed 67% -> 50 out of 75 batches.
Epoch 1 - Processed 80% -> 60 out of 75 batches.
Epoch 1 - Processed 93% -> 70 out of 75 batches.
Epoch 1 completed with average loss: 0.1344
Epoch 2 - Processed 13% -> 10 out of 75 batches.
Epoch 2 - Processed 27% -> 20 out of 75 batches.
Epoch 2 - Processed 40% -> 30 out of 75 batches.
Epoch 2 - Processed 53% -> 40 out of 75 batches.
Epoch 2 - Processed 67% -> 50 out of 75 batches.
Epoch 2 - Processed 80% -> 60 out of 75 batches.
Epoch 2 - Processed 93% -> 70 out of 75 batches.
Epoch 2 completed with average loss: 0.1058
Epoch 3 - Processed 13% -> 10 out of 75 batches.
Epoch 3 - Processed 27% -> 20 out of 75 batches.
Epoch 3 - Processed 40% -> 30 out of 75 batches.
Epoch 3 - Processed 53% -> 40 out of 75 batches.
Epoch 3 - Processed 67% -> 50 out of 75 batches.
Epoch 3 - Processed 80% -> 60 out of 75 batches.
Epoch 3 - Processed 93% -> 70 out of 75 batches.
Epoch 3 completed with average loss: 0.0641

## Post-Fine-Tuning Performance Evaluation
Recompute the cosine similarity for query and new_content pairs after fine-tuning.

In [14]:
# Post-fine-tuning similarity calculation with progress updates
similarities_after = []
model.eval()
for i, row in test_df.iterrows():
    query_embedding = get_embeddings(row['query'], model, tokenizer)
    content_embedding = get_embeddings(row['news_content'], model, tokenizer)
    similarity = cosine_similarity(query_embedding, content_embedding)[0][0]
    similarities_after.append(similarity)
    
    # Print progress
    if (i + 1) % 100 == 0:
        percent_complete = ((i + 1) / len(test_df)) * 100
        print(f"Processed {percent_complete:.0f}% -> {i + 1} out of {len(test_df)} rows.")

test_df['similarity_after'] = similarities_after
print("Average Post-Fine-Tuning Similarity:", sum(similarities_after) / len(similarities_after))

Processed 300% -> 1800 out of 600 rows.
Processed 17% -> 100 out of 600 rows.
Processed 100% -> 600 out of 600 rows.
Processed 267% -> 1600 out of 600 rows.
Processed 33% -> 200 out of 600 rows.
Processed 217% -> 1300 out of 600 rows.
Processed 233% -> 1400 out of 600 rows.
Average Post-Fine-Tuning Similarity: 0.94892925

## Save Results and compare

In [15]:
# Save the comparison results to CSV
test_df.to_csv('fine_tuning_results_test_set.csv', index=False)
print("Results saved to fine_tuning_results_test_set.csv")

# Display average similarity improvement
avg_similarity_before = test_df['similarity_before'].mean()
avg_similarity_after = test_df['similarity_after'].mean()
print(f"Average Similarity Before Fine-Tuning: {avg_similarity_before:.4f}")
print(f"Average Similarity After Fine-Tuning: {avg_similarity_after:.4f}")
print(f"Improvement: {avg_similarity_after - avg_similarity_before:.4f}")

Results saved to fine_tuning_results_test_set.csv
Average Similarity Before Fine-Tuning: 0.8460
Average Similarity After Fine-Tuning: 0.9489
Improvement: 0.1030

##  Save the Model and Tokenizer

In [16]:
from transformers import AutoModel

# Paths for saving base model and LoRA adapter
base_model_directory = "../models/fine_tuned_e5_large_v2_lora/base_model"
adapter_directory = "../models/fine_tuned_e5_large_v2_lora/adapter"

# Ensure the directories exist
import os
os.makedirs(base_model_directory, exist_ok=True)
os.makedirs(adapter_directory, exist_ok=True)

# Save the base model separately
base_model = AutoModel.from_pretrained("intfloat/e5-large-v2")
base_model.save_pretrained(base_model_directory)

# Save the adapter (fine-tuned LoRA weights)
model.save_pretrained(adapter_directory)

# Save the tokenizer in the main directory
tokenizer.save_pretrained("../models/fine_tuned_e5_large_v2_lora")

print(f"Base model saved to {base_model_directory}")
print(f"Adapter (fine-tuned model) saved to {adapter_directory}")
print("Tokenizer saved successfully.")

Base model saved to ../models/fine_tuned_e5_large_v2_lora/base_model
Adapter (fine-tuned model) saved to ../models/fine_tuned_e5_large_v2_lora/adapter
Tokenizer saved successfully.

In [17]:
# from transformers import AutoTokenizer

# # Define a path to save the model and tokenizer
# save_directory = "../models/fine_tuned_e5_large_v2_lora"

# # Save the fine-tuned model
# model.save_pretrained(save_directory)

# # Save the tokenizer
# tokenizer.save_pretrained(save_directory)

# print(f"Model and tokenizer saved to {save_directory}")

## Try the model on the news data set with more general queries

In [18]:
# Generate embeddings for all news items and store in 'embedding' column
df['e5_embedding'] = df['content'].apply(lambda x: get_embeddings(x, model, tokenizer))
df

,_id,title,pubDate,guid,link,description,content,openai_embedding,e5_embedding_before_tuning,e5_embedding
0,671e2d0aeccd4a5f4883e981,Justin Welby: Political leaders should treat o...,2024-01-01 00:00:04,https://www.bbc.co.uk/news/uk-67844356,https://www.bbc.co.uk/news/uk-67844356?at_medi...,The Archbishop of Canterbury urges politicians...,Justin Welby: Political leaders should treat o...,"[0.02301846444606781, -0.006470758933573961, 0...","[[0.51037025, -0.79349065, -0.13040037, -0.139...","[[0.3661322, -1.1412252, 0.17336315, -0.137644..."
1,671e2d0aeccd4a5f4883e982,Almost three million tested for cancer in England,2024-01-01 00:09:56,https://www.bbc.co.uk/news/health-67841348,https://www.bbc.co.uk/news/health-67841348?at_...,Record numbers are being tested for cancer but...,Almost three million tested for cancer in Engl...,"[0.0134049067273736, 0.012411133386194706, 0.0...","[[0.3748049, -1.0251585, -0.13934056, -0.46842...","[[0.25168958, -1.3728334, 0.1894472, -0.401590..."
2,671e2d0aeccd4a5f4883e983,Household energy price rise of 5% comes into f...,2024-01-01 00:00:16,https://www.bbc.co.uk/news/business-67785266,https://www.bbc.co.uk/news/business-67785266?a...,A higher cap for the next three months adds £9...,Household energy price rise of 5% comes into f...,"[-0.00222824071533978, 0.032821644097566605, 0...","[[0.5421233, -0.91381705, 0.37531197, -0.54616...","[[0.28375754, -1.2104545, 0.43982285, -0.32502..."
3,671e2d0aeccd4a5f4883e984,Primrose Hill stabbing: Harry Pitman named as ...,2024-01-01 17:11:13,https://www.bbc.co.uk/news/uk-england-london-6...,https://www.bbc.co.uk/news/uk-england-london-6...,"Harry Pitman, 16, was attacked on London's Pri...",Primrose Hill stabbing: Harry Pitman named as ...,"[-0.0027212619315832853, 0.003952309023588896,...","[[-0.32640272, -1.4084414, -0.064704806, -0.96...","[[-0.13805056, -1.6102695, 0.20174393, -0.8064..."
4,671e2d0aeccd4a5f4883e985,Israel Supreme Court strikes down judicial ref...,2024-01-01 19:47:58,https://www.bbc.co.uk/news/world-middle-east-6...,https://www.bbc.co.uk/news/world-middle-east-6...,The controversial plans triggered nationwide p...,Israel Supreme Court strikes down judicial ref...,"[0.026911897584795952, 0.025074539706110954, 0...","[[-0.28679425, -0.8542533, 0.63113433, -0.7137...","[[-0.12946197, -1.1774564, 0.642205, -0.448401..."
...,...,...,...,...,...,...,...,...,...,...
7255,671e2d0aeccd4a5f488405d8,Aer Lingus pilots stage eight-hour work stoppage,2024-06-29 13:49:48,https://www.bbc.com/news/articles/cpv3dg31x75o#12,https://www.bbc.com/news/articles/cpv3dg31x75o,"The strike action, which lasted for eight hour...",Aer Lingus pilots stage eight-hour work stoppa...,"[-0.03716661408543587, 0.040872685611248016, 0...","[[0.2114126, -0.6251888, -0.22534753, -0.19603...","[[0.22619294, -1.0267925, -0.01779555, -0.2222..."
7256,671e2d0aeccd4a5f488405d9,Another council sets up emergency postal vote ...,2024-06-29 12:43:00,https://www.bbc.com/news/articles/cx02knj0l7xo#12,https://www.bbc.com/news/articles/cx02knj0l7xo,Replacement voting packs are issued in some ar...,Another council sets up emergency postal vote ...,"[0.020275646820664406, 0.06969498842954636, 0....","[[-0.3025538, -1.7177178, 0.15702304, -0.68241...","[[-0.13594653, -1.744225, 0.29958287, -0.44506..."
7257,671e2d0aeccd4a5f488405da,"Politicians forget we're voters, says Gypsy woman",2024-06-29 21:00:01,https://www.bbc.com/news/articles/c3ggvyrk0k6o#12,https://www.bbc.com/news/articles/c3ggvyrk0k6o,A campaign group says Travellers are treated l...,"Politicians forget we're voters, says Gypsy wo...","[0.002537588821724057, 0.060002345591783524, -...","[[0.18100068, -1.0736654, 0.33410802, -0.26385...","[[0.15298942, -1.3693814, 0.47441474, -0.19119..."
7258,671e2d0aeccd4a5f488405db,Where are the seats that could decide the elec...,2024-06-25 14:49:05,https://www.bbc.com/news/articles/c133p016pg4o#1,https://www.bbc.com/news/articles/c133p016pg4o,The parties' top battleground targets across t...,Where are the seats that could decide the elec...,"[-0.01693105325102806, 0.05472404509782791, 0....","[[0.098247014, -1.6112999, 0.021881485, -0.790...","[[0.24087821, -1.5872864, 0.16925971, -0.45072..."
7259,671e2d0aeccd4a5f488405dc,"Penalties, red cards and shocks - England's 58...",2024-06-05 05:50:23,https://www.bbc.com/sport/football/articles/c5...,https://www.bbc.com/sport/football/articles/c5...,It has been 58 years since England's men last ...,"Penalties, red cards and shocks - England's 58...","[0.005774413701146841, 0.04007718339562416, 0....","[[-0.19958772, -1.2032546, -0.32741264, -0.791...","[[-0.1514334, -1.450588, 0.006339461, -0.54968..."

In [19]:
def find_top_news(query, df, model, tokenizer, top_k=10):
    query_embedding = get_embeddings(query, model, tokenizer)

    # Calculate cosine similarity between query and all news embeddings
    similarities = df['e5_embedding'].apply(lambda x: cosine_similarity(query_embedding, x)[0][0])
    
    # Add similarity scores to the DataFrame
    df['e5_similarity'] = similarities
    
    # Sort by similarity and return the top_k results
    top_matches = df.nlargest(top_k, 'e5_similarity')
    
    # Clean up by dropping the 'similarity' column
    df.drop(columns=['e5_similarity'], inplace=True)
    
    return top_matches[['content', 'e5_similarity']]

In [20]:
"""

"""
test_queries = ["Products for Color-blind people","JEEP off-road vehicles","What is the origin of Bamba snack","Recommended diet and exercise habits for managing obesity","Keep your children safe on the internet","What are the lates news about AI ethics?","How the war between Israel and Hamas is affecting global politics?","Latest trends in the fashion industry","Interest rates","biden vs trump","Best Marvel movie this year","Northern Lights"]
for user_query in test_queries:
    print(f"\n\nQuery: {user_query}")
    top_news = find_top_news(user_query, df, model, tokenizer)
    for _, row in top_news.iterrows():
                print(f"\033[96m Similarity: {row['e5_similarity']:.3f}::\033[0m {row['content']}")

Query: Products for Color-blind people
 Similarity: 0.907:: Ethnic bias in health devices 'puts patients at risk'. The review focuses on devices frequently used in the NHS, like pulse oximeters and skin cancer apps.
 Similarity: 0.903:: 'I’ve invented an alternative to uncomfortable smear tests'. Sânziana Foia's non-invasive test detects harmful virus strains and delivers fast results at home.
 Similarity: 0.901:: What is behind the TikTok thirst for Stanley water cups?. People are camping outside supermarkets in the US to try to buy the latest internet on-trend item.
 Similarity: 0.901:: Top sunscreens fail protection tests, Which? says. Some cheaper lotions from supermarkets Aldi and Lidl outperformed more expensive brands, Which? said.
 Similarity: 0.900:: Where workers are exploited to harvest an everyday ingredient. Brazilian workers face degrading conditions to harvest palm wax used in sweets, pills and lipstick.
 Similarity: 0.899:: How portable X-ray machines are helping remote patients. Portable X-ray equipment that can take high quality images is transforming healthcare in remote areas.
 Similarity: 0.899:: The explosions of colour that painted a Glasgow estate. Sony’s 2006 “Paint” advert is widely considered one of the most ambitious in history - but how was it made?
 Similarity: 0.898:: Cost of living: How can I make extra income?. Some people have been earning thousands selling clothes and other items since they were in school.
 Similarity: 0.898:: Warning over children using anti-ageing skincare products. Dermatologists say products with ingredients potentially harmful to children are growing popular.
 Similarity: 0.898:: Farnham penguin finds 'guide bird' in one of her friends. Partially-sighted Squid the penguin, who developed cataracts as a chick, now has a guide to help.


Query: JEEP off-road vehicles
 Similarity: 0.888:: How to drive in icy weather. Tips on what to carry in your car, and how to drive in snow and icy weather.
 Similarity: 0.883:: Our Range Rovers are not UK's most-stolen car, says Jaguar Land Rover. The boss of Jaguar Land Rover hits out at what he says is inaccurate reporting about the Range Rover.
 Similarity: 0.880:: UAE: A hailstorm in the desert? Rare weather phenomenon shocks residents. Large hailstones covered roads as a rare weather phenomenon hit the United Arab Emirates.
 Similarity: 0.879:: California: Rockslide blocking road cleared with explosives. Video shared by Placer County shows a road completely blocked by boulders, that are then blasted into small pieces.
 Similarity: 0.879:: Ingenuity: Damage puts end to ground-breaking Mars helicopter mission. The first vehicle to achieve powered flight on another planet suffers rotor damage three years into tour.
 Similarity: 0.878:: Watch: Wheelie bins fly and a caravan overturns in wind. Cars are damaged and houses shake as a suspected tornado strikes in Knutton, Staffordshire.
 Similarity: 0.878:: TV star shaken after Jaguar brakes fail during drive. Craig Phillips describes "terrifying feeling" when brakes failed on his Jaguar I-Pace
 Similarity: 0.877:: Six skiers missing near Matterhorn in Swiss Alps. The Swiss Alps have seen high winds for some days, and over the last 24 hours, heavy snowfalls.
 Similarity: 0.875:: Car slides on roof after drink-driver crash. Dashcam footage shows the car sliding along the carriageway with sparks flying out from underneath.
 Similarity: 0.874:: Giraffe Benito escapes extreme temperatures for new home. A giraffe is being moved 2,000km south from Ciudad Juárez in northern Mexico to more temperate climes.


Query: What is the origin of Bamba snack
 Similarity: 0.899:: Big Zuu cuts down on cooking and rap for Ramadan. The rapper and TV chef visited Mecca for the first time to explore his Muslim faith for a documentary.
 Similarity: 0.898:: Scientists grow 'meaty' rice hybrid food for protein kick. A team in South Korea say they have cracked how to grow beef muscle and fat cells inside grains of rice.
 Similarity: 0.894:: West Africa’s Michelin-starred cuisine wows London. African fine dining is often overlooked, but now restaurants are getting their just deserts.
 Similarity: 0.894:: What is behind the TikTok thirst for Stanley water cups?. People are camping outside supermarkets in the US to try to buy the latest internet on-trend item.
 Similarity: 0.892:: Giving babies smooth peanut butter could provide lifelong allergy defence. Risks of peanut allergy cut by 71% in teenagers who had peanut as a baby.
 Similarity: 0.892:: The Birmingham child who paved the way for the heel prick test. Sheila Jones, who had Phenylketonuria (PKU), was treated by pioneering doctors 70 years ago.
 Similarity: 0.891:: General Tso’s chicken to bento bowls: A food guide to Taiwan politics. Unique flavour combinations and profiles represent how Taiwan's unique identity is starting to take shape.
 Similarity: 0.891:: Hyena shocks Kenyan after sneaking into his shop. Fredrick Omungu opened his business in the morning to discover the animal hiding under the counter.
 Similarity: 0.891:: Moti Mahal: India curry houses battle over butter chicken. Butter chicken - a curry popular around the world - is now in the middle of a court battle in India.
 Similarity: 0.891:: Dancer with allergy eats mislabelled biscuit and dies. The British woman suffered anaphylactic shock after eating a mislabelled cookie from a US store.


Query: Recommended diet and exercise habits for managing obesity
 Similarity: 0.933:: Weighing up diet drugs. Obesity jabs 'could reduce heart attack risk' says new study
 Similarity: 0.912:: Katie Price low calorie diet advert banned. The social media post irresponsibly promoted a diet that fell below 800 calories a day, a watchdog says.
 Similarity: 0.911:: Doctors question science behind blood sugar diet trend. Experts say there is "no strong evidence" the monitors, proven to be effective in managing diabetes, can also help people without the condition.
 Similarity: 0.910:: Did bodybuilding bring on my early perimenopause?. Adele Johnston was 33 when she developed painful symptoms such as heart palpitations and itchy skin.
 Similarity: 0.909:: Wegovy, the 'Viagra' of weight-loss drugs flying off the shelves. How did Danish weight-loss treatment Wegovy become a global sales sensation?
 Similarity: 0.909:: May horrified to learn about risks of diabetes disordered eating. Better awareness and more NHS support are needed, the former prime minister says.
 Similarity: 0.907:: Why choosing whole grains can benefit our health. Why choosing whole grains can help your heart, your microbiome and your blood sugar.
 Similarity: 0.907:: Just five more ways Michael Mosley made us healthier. Michael Mosley’s simple and accessible health hacks made him a household name.  Remember these?
 Similarity: 0.905:: Why fat Labradors can blame their genes. Scientists used the 'sausage in a box' test to find out that dogs can be a "hard-wired" for obesity.
 Similarity: 0.905:: Scientists grow 'meaty' rice hybrid food for protein kick. A team in South Korea say they have cracked how to grow beef muscle and fat cells inside grains of rice.


Query: Keep your children safe on the internet
 Similarity: 0.928:: Bereaved parents win online harm battle. Tech firms will have to hand over personal data of children whose death may be related to online harm.
 Similarity: 0.925:: Tame toxic algorithms to protect children, big tech told. Big tech companies will have to make changes to their algorithms to comply with new online safety laws.
 Similarity: 0.925:: Brianna Ghey's mother and Molly Russell's father join forces to combat online harm. Esther Ghey and Ian Russell want better protection for teenagers on social media.
 Similarity: 0.919:: Tech firms told to hide 'toxic' content from children. Social media firms like Instagram and TikTok will have to make changes to comply with new online safety laws.
 Similarity: 0.917:: Meta tool to block nude images in teens' private messages. The move is designed to help stop teenagers receiving inappropriate pictures, even in encrypted chats
 Similarity: 0.916:: Police investigate virtual sex assault on girl's avatar. The incident in a virtual world reportedly left the under-16-year-old traumatised.
 Similarity: 0.913:: Pupils get rare alert over dangers of sextortion. The National Crime Agency says young boys are increasingly being targeted by gangs.
 Similarity: 0.909:: US health chief wants smoking-style warning labels on social media. Vivek Murthy says social media increases the risk that children will experience anxiety and depression.
 Similarity: 0.909:: New law aims to protect devices from hackers. Speakers, fitness trackers and other internet-connected devices sold in the UK now have to meet new requirements.
 Similarity: 0.909:: Back-to-school illness advice offered to parents. Health officials explain when to keep your child at home and how to stop the spread of bugs.


Query: What are the lates news about AI ethics?
 Similarity: 0.936:: AI and humanity’s future: chilling or thrilling?. Amol & Nick take on Stephen Fry’s challenge & look at what the future of AI might entail.
 Similarity: 0.934:: Urgent need for terrorism AI laws, warns think tank. The government should 'urgently consider' AI-specific legislation a think-tank says.
 Similarity: 0.931:: Concern rises over AI in adult entertainment. AI in adult entertainment could have negative effects on society and individuals, experts say.
 Similarity: 0.931:: How AI is being used to prevent illegal fishing. Illegal fishing remains a huge global problem, but AI is now being used to tackle the issue.
 Similarity: 0.931:: AI could 'supercharge' election disinformation, US tells the BBC. US Deputy Attorney General Lisa Monaco says the US wants tougher sentences for crimes involving AI.
 Similarity: 0.930:: New version of Chat-GPT can teach maths and flirt . OpenAI has unveiled a new, faster version of its generative AI tool, ChatGPT.
 Similarity: 0.930:: Apple brings ChatGPT to iPhones in AI overhaul. The company has been slower to roll out generative AI features than rivals including Google and Microsoft.
 Similarity: 0.929:: What happens when you think AI is lying about you?. BBC Tech Editor Zoe Kleinman tried to challenge the output of a chatbot - but all was not as it seemed.
 Similarity: 0.929:: CES 2024: AI pillows and toothbrushes - is it all getting a bit silly?. Companies are clamouring to present their products as AI-powered, but are their claims justified?
 Similarity: 0.928:: How AI is helping to prevent future power cuts. Artificial intelligence software is being used to predict electricity demand and supply.


Query: How the war between Israel and Hamas is affecting global politics?
 Similarity: 0.946:: Chris Mason: How Gaza conflict is contorting UK politics. The Conservatives, Labour, and Parliament itself are finding themselves torn by the furious arguments provoked by the Israel-Gaza war.
 Similarity: 0.942:: Israel-Palestinian bitterness deepened by Hamas attack and war. Both Israelis and Palestinians believe the world does not understand their pain and suffering.
 Similarity: 0.941:: Have Iran-Israel missile strikes changed the Middle East?. Political and military leaders are still absorbing the extraordinary exchange of fire, writes James Landale.
 Similarity: 0.940:: Could the Israel-Gaza war cost Biden the election?. The President’s said he’s 'outraged' by aid worker killings
 Similarity: 0.940:: Israel-Gaza war: Latest ceasefire talks not very promising - Qatar. Israel's PM Benjamin Netanyahu vows to carry on the war against Hamas regardless of international pressure.
 Similarity: 0.940:: Jeremy Bowen: What ICC arrest warrants mean for Israel and Hamas. The Israeli and Hamas leaders are suspected of committing war crimes during the continuing war in Gaza.
 Similarity: 0.940:: How plans for ‘the day after’ could help end war in Gaza. This subject will be on the table when EU and Middle Eastern foreign ministers meet.
 Similarity: 0.939:: No let-up for Gazans while world focused on Iran attacks. Fighting continues in Gaza, where a humanitarian crisis is overshadowed by the wider regional conflict.
 Similarity: 0.939:: Why have Israel and Iran attacked each other?. The long-running shadow war between the two countries has come into the open.
 Similarity: 0.937:: Strikes on Houthi targets in Yemen show war in Gaza has already spread. War spreading in the Middle East is not just a risk - it has already happened, writes the BBC's international editor.


Query: Latest trends in the fashion industry
 Similarity: 0.919:: How Zendaya perfected 'method dressing'. Film stars have made fancy dress fashionable in their recent red carpet looks.
 Similarity: 0.918:: Champagne, caffeine and chaos: Fashion week descends on Paris. Louis Vuitton, Dior, Hermes, Rick Owens, Loewe, Kenzo and Dries Van Noten all introduce new collections in Paris.
 Similarity: 0.912:: The most eye-catching looks from the Met Gala so far. Lea Michelle, Zendaya and Gigi Hadid are among the stars walking the red carpet.
 Similarity: 0.912:: In pictures:  Daisy's hot pants and other striking outfits from the red carpet. Big names from films like Barbie, Oppenheimer and Saltburn step out at the British awards ceremony.
 Similarity: 0.911:: Stars take over Paris for sporty Vogue fashion show. Supermodels, singers and sports star took to the runway in Paris as Vogue turned a square into a runway.
 Similarity: 0.909:: Zendaya and Kim Kardashian stun on Met Gala red carpet. The celebrities are showing up for fashion's night of nights in New York City.
 Similarity: 0.908:: ‘Insane’ journey for NI supermodel from grammar school to Dior. Omagh teenager Alice McGrath is the latest face of high fashion after being discovered online.
 Similarity: 0.908:: Vinted makes first profit on used fashion. The second-hand fashion marketplace is the first of the new "pre-loved" clothing platforms to make a profit.
 Similarity: 0.907:: Victoria Beckham's fashion show disrupted by Peta. The 49-year-old Spice Girl was showcasing her label's autumn/winter collection at Paris Fashion Week.
 Similarity: 0.907:: In pictures: London Fashion Week's big moments. A surprise appearance from the supermodel topped off the 40th anniversary celebrations.


Query: Interest rates
 Similarity: 0.935:: Interest rates expected to be held at 5.25%. Despite inflation falling to 2%, experts are expecting interest rates to be held at a 16-year high.
 Similarity: 0.930:: When will UK interest rates come down?. Bank of England interest rates affect mortgage, loan and savings rates for millions of people.
 Similarity: 0.929:: What are UK interest rates and when will they fall?. Bank of England interest rates affect the mortgage, loan and savings rates for millions of people.
 Similarity: 0.929:: How do interest rates affect me?. Bank of England interest rates have an impact on the mortgage, loan and savings rates for millions of people.
 Similarity: 0.927:: Interest rate cuts 'on the way', says Bank boss. The Bank of England has kept the cost of borrowing at 5.25% for the fifth time in a row.
 Similarity: 0.925:: Bank of England expected to hold interest rates. The Bank is widely expected to keep rates at 5.25% for now, but cut them later in the year.
 Similarity: 0.923:: Mortgage lenders rapidly changing interest rates. HSBC, NatWest and Virgin Money are all increasing mortgage rates continuing a frantic start to the year.
 Similarity: 0.922:: Bank 'optimistic' as it edges closer to summer cut. Its comments came as UK interest rates were left unchanged at a 16-year high of 5.25%.
 Similarity: 0.922:: Inflation and Covid set our savings back 10 years. Justin Williams is one of many whose savings have eroded and mortgage rates have increased.
 Similarity: 0.921:: Homeowner pain as major banks hike mortgage rates. Lenders respond over views the Bank of England may not cut interest rates as soon as previously thought.


Query: biden vs trump
 Similarity: 0.940:: Super Tuesday: Everything Points to Trump vs Biden. Trump and Biden win almost every state in election season's biggest primary night.
 Similarity: 0.939:: Where Biden and Trump stand on key issues. How the two candidates' policies compare on the economy, immigration, abortion and other big issues.
 Similarity: 0.939:: What to watch for at Biden and Trump's first debate. The BBC's Sarah Smith looks at what's at stake for both men as they prove they're worth a second White House term.
 Similarity: 0.937:: Illegal migration, tax and abortion - fact checking Trump-Biden debate. BBC Verify looks into various claims made on stage by Donald Trump and Joe Biden.
 Similarity: 0.937:: Big stakes and high tension as Biden-Trump debate looms. Thursday's debate between the two will be a reunion of sorts - although not exactly a friendly one.
 Similarity: 0.934:: 'A reality show': World reacts to Trump-Biden debate . Global reviews were most scathing of Mr Biden, but his Republican challenger did not escape criticism.
 Similarity: 0.934:: Biden and Trump make competing trips to US border. The two likely presidential candidates make speeches in an effort to show they can tackle illegal crossings.
 Similarity: 0.933:: Watch key moments from Biden and Trump's first debate. The pair threw insults and clashed on stage about the biggest issues American voters care about - here's what they said.
 Similarity: 0.932:: Biden faces high-stakes address to calm Democratic nerves. The president will seek to fight concerns over his age and contrast his term in office with Donald Trump's.
 Similarity: 0.930:: Biden says he's ready for election debate with Trump. US President says he is "happy" to face rival who claims he is ready "anytime, anywhere, anyplace".


Query: Best Marvel movie this year
 Similarity: 0.901:: Marvel star Jeremy Renner: I'm so blessed a year after accident. The Marvel star reflects on his recovery after being run over by his own snow plough last New Year's Day.
 Similarity: 0.899:: Oscars 2024: Poor Things and Anatomy of a Fall scoop early awards. Best picture favourite Oppenheimer has 13 nominations and could become one of the biggest winners of all time.
 Similarity: 0.896:: Oppenheimer among Bafta best film nominees. Barbie was the top grossing film of 2023 and received great reviews, but missed out on a best film nomination.
 Similarity: 0.895:: Oppenheimer: Cillian Murphy film marches towards Oscars success. Christopher Nolan's film got another boost in its awards campaign at last week's Golden Globes.
 Similarity: 0.894:: Bafta nominations 2024: The full list of film contenders. Oppenheimer and Poor Things are the leading contenders for this year's British Academy Film Awards.
 Similarity: 0.894:: Oppenheimer's Cillian Murphy and Robert Downey Jr scoop Bafta Film Awards. Cillian Murphy, Robert Downey Jr and Christopher Nolan all win Bafta Film Awards for Oppenheimer.
 Similarity: 0.894:: Tom Holland's Romeo wows crowds more than critics. Reviews describe the Spider-Man star's performance on stage as "good", "fine" and "perfectly OK".
 Similarity: 0.891:: Marvel star Karen Gillan is not scared of being cancelled . Scots actress Karen Gillan's new role made her face up to the pitfalls of social media.
 Similarity: 0.891:: Deadpool 3 and Wicked trailers air in Super Bowl adverts. Fans were given a first look at the upcoming films during Sunday night's NFL showdown.
 Similarity: 0.891:: Madame Web: Critics savage Dakota Johnson's Spider-Man spin-off. The trailer went viral for how awful it was, and the film has not fared much better with critics.


Query: Northern Lights
 Similarity: 0.937:: Northern lights give spectacular surprise display across UK. In a sudden display the aurora was seen from the Highlands down to Cornwall on Sunday night.

## Loading the Fine-Tuned Model for Embeddings in Your App

In [21]:
from transformers import AutoTokenizer, AutoModel

save_directory = "../models/fine_tuned_e5_large_v2_lora"

# Load the fine-tuned model and tokenizer
model = AutoModel.from_pretrained(save_directory)
tokenizer = AutoTokenizer.from_pretrained(save_directory)

# Now you can use `model` for embeddings in your app

ValueError: Unrecognized model in ../models/fine_tuned_e5_large_v2_lora. Should have a `model_type` key in its config.json, or contain one of the following strings in its name: albert, align, altclip, audio-spectrogram-transformer, autoformer, bark, bart, beit, bert, bert-generation, big_bird, bigbird_pegasus, biogpt, bit, blenderbot, blenderbot-small, blip, blip-2, bloom, bridgetower, bros, camembert, canine, chameleon, chinese_clip, chinese_clip_vision_model, clap, clip, clip_text_model, clip_vision_model, clipseg, clvp, code_llama, codegen, cohere, conditional_detr, convbert, convnext, convnextv2, cpmant, ctrl, cvt, dac, data2vec-audio, data2vec-text, data2vec-vision, dbrx, deberta, deberta-v2, decision_transformer, deformable_detr, deit, depth_anything, deta, detr, dinat, dinov2, distilbert, donut-swin, dpr, dpt, efficientformer, efficientnet, electra, encodec, encoder-decoder, ernie, ernie_m, esm, falcon, falcon_mamba, fastspeech2_conformer, flaubert, flava, fnet, focalnet, fsmt, funnel, fuyu, gemma, gemma2, git, glpn, gpt-sw3, gpt2, gpt_bigcode, gpt_neo, gpt_neox, gpt_neox_japanese, gptj, gptsan-japanese, granite, granitemoe, graphormer, grounding-dino, groupvit, hiera, hubert, ibert, idefics, idefics2, imagegpt, informer, instructblip, instructblipvideo, jamba, jetmoe, jukebox, kosmos-2, layoutlm, layoutlmv2, layoutlmv3, led, levit, lilt, llama, llava, llava_next, llava_next_video, llava_onevision, longformer, longt5, luke, lxmert, m2m_100, mamba, mamba2, marian, markuplm, mask2former, maskformer, maskformer-swin, mbart, mctct, mega, megatron-bert, mgp-str, mimi, mistral, mixtral, mllama, mobilebert, mobilenet_v1, mobilenet_v2, mobilevit, mobilevitv2, mpnet, mpt, mra, mt5, musicgen, musicgen_melody, mvp, nat, nemotron, nezha, nllb-moe, nougat, nystromformer, olmo, olmoe, omdet-turbo, oneformer, open-llama, openai-gpt, opt, owlv2, owlvit, paligemma, patchtsmixer, patchtst, pegasus, pegasus_x, perceiver, persimmon, phi, phi3, pix2struct, pixtral, plbart, poolformer, pop2piano, prophetnet, pvt, pvt_v2, qdqbert, qwen2, qwen2_audio, qwen2_audio_encoder, qwen2_moe, qwen2_vl, rag, realm, recurrent_gemma, reformer, regnet, rembert, resnet, retribert, roberta, roberta-prelayernorm, roc_bert, roformer, rt_detr, rt_detr_resnet, rwkv, sam, seamless_m4t, seamless_m4t_v2, segformer, seggpt, sew, sew-d, siglip, siglip_vision_model, speech-encoder-decoder, speech_to_text, speech_to_text_2, speecht5, splinter, squeezebert, stablelm, starcoder2, superpoint, swiftformer, swin, swin2sr, swinv2, switch_transformers, t5, table-transformer, tapas, time_series_transformer, timesformer, timm_backbone, trajectory_transformer, transfo-xl, trocr, tvlt, tvp, udop, umt5, unispeech, unispeech-sat, univnet, upernet, van, video_llava, videomae, vilt, vipllava, vision-encoder-decoder, vision-text-dual-encoder, visual_bert, vit, vit_hybrid, vit_mae, vit_msn, vitdet, vitmatte, vits, vivit, wav2vec2, wav2vec2-bert, wav2vec2-conformer, wavlm, whisper, xclip, xglm, xlm, xlm-prophetnet, xlm-roberta, xlm-roberta-xl, xlnet, xmod, yolos, yoso, zoedepth

## Generate Embeddings with the Loaded Model

In [11]:
import torch

def get_embeddings(text, model, tokenizer):
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True)
    with torch.no_grad():
        embeddings = model(**inputs).last_hidden_state.mean(dim=1).cpu().numpy()
    return embeddings

# Example usage
text = "Example query for embedding generation"
embedding = get_embeddings(text, model, tokenizer)
embedding

# Fine-tuning using less data

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split

from pymongo import MongoClient
import pandas as pd

# MongoDB connection details
mongo_uri = "mongodb://localhost:27017/"
db_name = "task1"
collection_name = "bbc_news"

# Connect to MongoDB
client = MongoClient(mongo_uri)
db = client[db_name]
collection = db[collection_name]

documents = list(collection.find())
df = pd.DataFrame(documents)
client.close()

queries_df = pd.read_csv('notebooks_data/generated_queries.csv')
queries_df = queries_df.iloc[:1000]

train_df, test_df = train_test_split(queries_df, test_size=0.3, random_state=42)
print(f"Training set size: {len(train_df)}")
print(f"Test set size: {len(test_df)}")

from transformers import AutoTokenizer, AutoModel
from peft import LoraConfig, get_peft_model

# Load tokenizer and model without quantization
model_name = "intfloat/e5-large-v2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)  # Standard loading, no quantization

# Define QLoRA configuration
lora_config = LoraConfig(
    r=8,               # Rank of the low-rank matrices
    lora_alpha=8,      # Scaling factor for LoRA updates
    target_modules=["key", "query", "value"],  # Adjust based on model structure if necessary
    lora_dropout=0.1,   # Dropout for LoRA layers
    bias="none"         # Exclude biases to focus on core layers
)

# Wrap the model with QLoRA
model = get_peft_model(model, lora_config)

Training set size: 700
Test set size: 300

In [4]:
import torch

def get_embeddings(text, model, tokenizer):
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True).to("cpu")
    with torch.no_grad():
        embeddings = model(**inputs).last_hidden_state.mean(dim=1).cpu().numpy()
    return embeddings


df['e5_embedding_before_tuning'] = df['content'].apply(lambda x: get_embeddings(x, model, tokenizer))

from sklearn.metrics.pairwise import cosine_similarity

def find_top_news(query, df, model, tokenizer, top_k=10):
    query_embedding = get_embeddings(query, model, tokenizer)

    # Calculate cosine similarity between query and all news embeddings
    similarities = df['e5_embedding_before_tuning'].apply(lambda x: cosine_similarity(query_embedding, x)[0][0])
    
    # Add similarity scores to the DataFrame
    df['e5_similarity'] = similarities
    
    # Sort by similarity and return the top_k results
    top_matches = df.nlargest(top_k, 'e5_similarity')
    
    # Clean up by dropping the 'similarity' column
    df.drop(columns=['e5_similarity'], inplace=True)
    
    return top_matches[['content', 'e5_similarity']]

test_queries = ["Products for Color-blind people","JEEP off-road vehicles","What is the origin of Bamba snack","Recommended diet and exercise habits for managing obesity","Keep your children safe on the internet","What are the lates news about AI ethics?","How the war between Israel and Hamas is affecting global politics?","Latest trends in the fashion industry","Interest rates","biden vs trump","Best Marvel movie this year","Northern Lights"]
for user_query in test_queries:
    print(f"\n\nQuery: {user_query}")
    top_news = find_top_news(user_query, df, model, tokenizer)
    for _, row in top_news.iterrows():
                print(f"\033[96m Similarity: {row['e5_similarity']:.3f}::\033[0m {row['content']}")

Query: Products for Color-blind people
 Similarity: 0.785:: Cost of living: How can I make extra income?. Some people have been earning thousands selling clothes and other items since they were in school.
 Similarity: 0.780:: Ethnic bias in health devices 'puts patients at risk'. The review focuses on devices frequently used in the NHS, like pulse oximeters and skin cancer apps.
 Similarity: 0.774:: Americanswers! What is Project 2025? Will Biden take a cognitive test?. We answer your questions on the biggest issues in the run-up to the election
 Similarity: 0.774:: Electioncast: Laura Kuenssberg and Adam Fleming answer your questions. Adam and Laura answer your election questions
 Similarity: 0.773:: The List. Exploring 9 amazing space missions.
 Similarity: 0.773:: Who can I vote for in the general election?. Find out which constituency you are in, who you can vote for and where you can vote using our postcode search.
 Similarity: 0.773:: 'I’ve invented an alternative to uncomfortable smear tests'. Sânziana Foia's non-invasive test detects harmful virus strains and delivers fast results at home.
 Similarity: 0.772:: Cost of living payments: What are they and who gets them?. Millions of low-income households will receive a final cost of living payment soon.
 Similarity: 0.772:: Aphantasia: Why I cannot see my children in my mind. Not everyone can picture images in their mind's eye and remember sounds or faces - but why?
 Similarity: 0.770:: Musician with hearing loss makes music from nature. A musician who lost her hearing overnight says it spurred her on to make new music from nature.


Query: JEEP off-road vehicles
 Similarity: 0.765:: How to drive in icy weather. Tips on what to carry in your car, and how to drive in snow and icy weather.
 Similarity: 0.740:: Watch: Wheelie bins fly and a caravan overturns in wind. Cars are damaged and houses shake as a suspected tornado strikes in Knutton, Staffordshire.
 Similarity: 0.740:: Our Range Rovers are not UK's most-stolen car, says Jaguar Land Rover. The boss of Jaguar Land Rover hits out at what he says is inaccurate reporting about the Range Rover.
 Similarity: 0.740:: Collapsing cliffs and washed-out roads after California storms. Days of heavy rainfall in California have caused flooding and mudslides, leaving infrastructure damaged.
 Similarity: 0.740:: Adults and teens turn to 'dumbphones'  to cut screen time. Parents and teens alike are trading in their smartphones for "dumber" models to help stay offline.
 Similarity: 0.739:: TV star shaken after Jaguar brakes fail during drive. Craig Phillips describes "terrifying feeling" when brakes failed on his Jaguar I-Pace
 Similarity: 0.736:: UAE: A hailstorm in the desert? Rare weather phenomenon shocks residents. Large hailstones covered roads as a rare weather phenomenon hit the United Arab Emirates.
 Similarity: 0.736:: California: Rockslide blocking road cleared with explosives. Video shared by Placer County shows a road completely blocked by boulders, that are then blasted into small pieces.
 Similarity: 0.735:: Have the wheels come off for Tesla?. As the electric carmaker sees sales fall and cuts jobs, we take a closer look at its problems.
 Similarity: 0.733:: Walkers forced to trespass onto open access countryside. Right to roam campaigners say hundreds of "open country" locations are inaccessible to the public.


Query: What is the origin of Bamba snack
 Similarity: 0.756:: The Birmingham child who paved the way for the heel prick test. Sheila Jones, who had Phenylketonuria (PKU), was treated by pioneering doctors 70 years ago.
 Similarity: 0.756:: Big Zuu cuts down on cooking and rap for Ramadan. The rapper and TV chef visited Mecca for the first time to explore his Muslim faith for a documentary.
 Similarity: 0.755:: Nigeria's love-hate relationship with twins. Two communities with different views about twins that meant the difference between life and death.
 Similarity: 0.755:: Kamila Valieva claimed contaminated strawberry dessert behind positive test. Banned figure skater Kamila Valieva claimed her positive doping test may have been caused by a contaminated strawberry dessert.
 Similarity: 0.754:: Scientists grow 'meaty' rice hybrid food for protein kick. A team in South Korea say they have cracked how to grow beef muscle and fat cells inside grains of rice.
 Similarity: 0.752:: Come Dine With Me winners part of drug import plot. Members of a gang to import cannabis were foiled after reports of a theft, police say.
 Similarity: 0.752:: One Love: How Kingsley Ben-Adir became Bob Marley on the set of Barbie. The actor initially turned down the role, saying it was too risky. What changed his mind?
 Similarity: 0.752:: Raisin found in toddler's nose after three-month mystery. Three-year-old Peyton Handley told her parents that she had a pain and would scratch around her nose.
 Similarity: 0.752:: The real story behind Bohemian Rhapsody. The full story behind Queen's iconic song.
 Similarity: 0.751:: Squirrels may have given medieval Britons leprosy. It’s the first time a medieval animal has been identified as a host for the disease.


Query: Recommended diet and exercise habits for managing obesity
 Similarity: 0.827:: Weighing up diet drugs. Obesity jabs 'could reduce heart attack risk' says new study
 Similarity: 0.797:: How do I register to vote?. Here’s what you need to know about how you register to vote and when.
 Similarity: 0.794:: Are we being tricked by our fitness trackers?. How accurate are fitness trackers?
 Similarity: 0.790:: Post Christmas debt: Which bills should I pay first?. What help and options are available to people struggling with debt repayments?
 Similarity: 0.788:: How to drive in icy weather. Tips on what to carry in your car, and how to drive in snow and icy weather.
 Similarity: 0.785:: What can I do if I can't pay my energy bill?. If you're struggling to afford your gas and electricity bills, what options are available?
 Similarity: 0.784:: How to win an Oscar. The campaigning behind the Academy Awards
 Similarity: 0.781:: Dog attacks: What can you do to protect yourself?. The best course of action will vary depending on the situation, dog behaviour experts explain.
 Similarity: 0.781:: Everything you need to know about student loans. How do they work across the UK, what can I borrow and when do I have to start paying it back?
 Similarity: 0.781:: Who can I vote for in the general election?. Find out which constituency you are in, who you can vote for and where you can vote using our postcode search.


Query: Keep your children safe on the internet
 Similarity: 0.820:: Tame toxic algorithms to protect children, big tech told. Big tech companies will have to make changes to their algorithms to comply with new online safety laws.
 Similarity: 0.816:: Brianna Ghey's mother and Molly Russell's father join forces to combat online harm. Esther Ghey and Ian Russell want better protection for teenagers on social media.
 Similarity: 0.815:: Bereaved parents win online harm battle. Tech firms will have to hand over personal data of children whose death may be related to online harm.
 Similarity: 0.806:: Tech firms told to hide 'toxic' content from children. Social media firms like Instagram and TikTok will have to make changes to comply with new online safety laws.
 Similarity: 0.800:: Back-to-school illness advice offered to parents. Health officials explain when to keep your child at home and how to stop the spread of bugs.
 Similarity: 0.798:: Rochdale abuse scandal: Inside the team fighting child sexual exploitation. How are police and child protection experts trying to prevent a repeat of the Rochdale abuse scandal?
 Similarity: 0.795:: Meta tool to block nude images in teens' private messages. The move is designed to help stop teenagers receiving inappropriate pictures, even in encrypted chats
 Similarity: 0.791:: Police investigate virtual sex assault on girl's avatar. The incident in a virtual world reportedly left the under-16-year-old traumatised.
 Similarity: 0.791:: New law aims to protect devices from hackers. Speakers, fitness trackers and other internet-connected devices sold in the UK now have to meet new requirements.
 Similarity: 0.788:: Pupils get rare alert over dangers of sextortion. The National Crime Agency says young boys are increasingly being targeted by gangs.


Query: What are the lates news about AI ethics?
 Similarity: 0.806:: AI and humanity’s future: chilling or thrilling?. Amol & Nick take on Stephen Fry’s challenge & look at what the future of AI might entail.
 Similarity: 0.805:: Concern rises over AI in adult entertainment. AI in adult entertainment could have negative effects on society and individuals, experts say.
 Similarity: 0.804:: How AI is being used to prevent illegal fishing. Illegal fishing remains a huge global problem, but AI is now being used to tackle the issue.
 Similarity: 0.804:: CES 2024: AI pillows and toothbrushes - is it all getting a bit silly?. Companies are clamouring to present their products as AI-powered, but are their claims justified?
 Similarity: 0.803:: New version of Chat-GPT can teach maths and flirt . OpenAI has unveiled a new, faster version of its generative AI tool, ChatGPT.
 Similarity: 0.801:: How AI is helping to prevent future power cuts. Artificial intelligence software is being used to predict electricity demand and supply.
 Similarity: 0.799:: AI could 'supercharge' election disinformation, US tells the BBC. US Deputy Attorney General Lisa Monaco says the US wants tougher sentences for crimes involving AI.
 Similarity: 0.799:: Urgent need for terrorism AI laws, warns think tank. The government should 'urgently consider' AI-specific legislation a think-tank says.
 Similarity: 0.798:: AI will not be the destroyer of jobs - Bank chief. Bank of England governor says AI has "great potential" as Lords report urges UK to embrace AI.
 Similarity: 0.795:: AI photos show people with cancer their lost future. People with secondary breast cancer view photos of themselves at events they may not live to see.


Query: How the war between Israel and Hamas is affecting global politics?
 Similarity: 0.840:: Israel-Palestinian bitterness deepened by Hamas attack and war. Both Israelis and Palestinians believe the world does not understand their pain and suffering.
 Similarity: 0.836:: Chris Mason: How Gaza conflict is contorting UK politics. The Conservatives, Labour, and Parliament itself are finding themselves torn by the furious arguments provoked by the Israel-Gaza war.
 Similarity: 0.831:: Could the Israel-Gaza war cost Biden the election?. The President’s said he’s 'outraged' by aid worker killings
 Similarity: 0.829:: Jeremy Bowen: What ICC arrest warrants mean for Israel and Hamas. The Israeli and Hamas leaders are suspected of committing war crimes during the continuing war in Gaza.
 Similarity: 0.820:: Why have Israel and Iran attacked each other?. The long-running shadow war between the two countries has come into the open.
 Similarity: 0.819:: Jeremy Bowen: Obstacles to peace seem larger than ever. The risk of an all-out Middle East war is increasing as the crisis in Gaza grows ever more desperate.
 Similarity: 0.819:: No let-up for Gazans while world focused on Iran attacks. Fighting continues in Gaza, where a humanitarian crisis is overshadowed by the wider regional conflict.
 Similarity: 0.818:: Lyse Doucet: Hamas leader's assassination sparks wider war fears. Lyse Doucet assesses if Hezbollah and Hamas will retaliate after Saleh al-Arouri was killed in Lebanon.
 Similarity: 0.818:: Have Iran-Israel missile strikes changed the Middle East?. Political and military leaders are still absorbing the extraordinary exchange of fire, writes James Landale.
 Similarity: 0.818:: Israel-Gaza war: Latest ceasefire talks not very promising - Qatar. Israel's PM Benjamin Netanyahu vows to carry on the war against Hamas regardless of international pressure.


Query: Latest trends in the fashion industry
 Similarity: 0.806:: How Zendaya perfected 'method dressing'. Film stars have made fancy dress fashionable in their recent red carpet looks.
 Similarity: 0.792:: Champagne, caffeine and chaos: Fashion week descends on Paris. Louis Vuitton, Dior, Hermes, Rick Owens, Loewe, Kenzo and Dries Van Noten all introduce new collections in Paris.
 Similarity: 0.790:: Egg Freezing and Me. Inside the world of one of the fastest growing fertility treatments in the UK.
 Similarity: 0.786:: The new language changing the dating scene. If you WLTM a ND with a GSOH, you might struggle to locate one on a modern dating app.
 Similarity: 0.785:: Kuenssberg: Are the politics of climate change going out of fashion?. Debate is shifting to cost concerns as net zero targets fast approach, says Laura Kuenssberg.
 Similarity: 0.781:: Cambodia: Fast fashion helps fuel blazing kilns where workers faint from heat. How hot is too hot to work? The BBC visits Cambodia's sweltering brick kilns to find out.
 Similarity: 0.780:: Stars take over Paris for sporty Vogue fashion show. Supermodels, singers and sports star took to the runway in Paris as Vogue turned a square into a runway.
 Similarity: 0.780:: Robot Ships. The revolution in shipping using 'ghost' vessels with hardly any crew on board.
 Similarity: 0.780:: The most eye-catching looks from the Met Gala so far. Lea Michelle, Zendaya and Gigi Hadid are among the stars walking the red carpet.
 Similarity: 0.780:: Zendaya and Kim Kardashian stun on Met Gala red carpet. The celebrities are showing up for fashion's night of nights in New York City.


Query: Interest rates
 Similarity: 0.837:: What are UK interest rates and when will they fall?. Bank of England interest rates affect the mortgage, loan and savings rates for millions of people.
 Similarity: 0.836:: Interest rates expected to be held at 5.25%. Despite inflation falling to 2%, experts are expecting interest rates to be held at a 16-year high.
 Similarity: 0.834:: How do interest rates affect me?. Bank of England interest rates have an impact on the mortgage, loan and savings rates for millions of people.
 Similarity: 0.832:: When will UK interest rates come down?. Bank of England interest rates affect mortgage, loan and savings rates for millions of people.
 Similarity: 0.832:: Inflation and Covid set our savings back 10 years. Justin Williams is one of many whose savings have eroded and mortgage rates have increased.
 Similarity: 0.825:: Mortgage lenders rapidly changing interest rates. HSBC, NatWest and Virgin Money are all increasing mortgage rates continuing a frantic start to the year.
 Similarity: 0.825:: Bank of England expected to hold interest rates. The Bank is widely expected to keep rates at 5.25% for now, but cut them later in the year.
 Similarity: 0.824:: Interest rate cuts 'on the way', says Bank boss. The Bank of England has kept the cost of borrowing at 5.25% for the fifth time in a row.
 Similarity: 0.820:: Interest rates won't fall due to 4% inflation, says Bank boss. Bank of England boss says the latest inflation figure "pretty much leaves us where we were".
 Similarity: 0.819:: Bank 'optimistic' as it edges closer to summer cut. Its comments came as UK interest rates were left unchanged at a 16-year high of 5.25%.


Query: biden vs trump
 Similarity: 0.856:: Super Tuesday: Everything Points to Trump vs Biden. Trump and Biden win almost every state in election season's biggest primary night.
 Similarity: 0.852:: Where Biden and Trump stand on key issues. How the two candidates' policies compare on the economy, immigration, abortion and other big issues.
 Similarity: 0.850:: Illegal migration, tax and abortion - fact checking Trump-Biden debate. BBC Verify looks into various claims made on stage by Donald Trump and Joe Biden.
 Similarity: 0.847:: Watch key moments from Biden and Trump's first debate. The pair threw insults and clashed on stage about the biggest issues American voters care about - here's what they said.
 Similarity: 0.847:: What to watch for at Biden and Trump's first debate. The BBC's Sarah Smith looks at what's at stake for both men as they prove they're worth a second White House term.
 Similarity: 0.845:: Biden faces high-stakes address to calm Democratic nerves. The president will seek to fight concerns over his age and contrast his term in office with Donald Trump's.
 Similarity: 0.843:: Big stakes and high tension as Biden-Trump debate looms. Thursday's debate between the two will be a reunion of sorts - although not exactly a friendly one.
 Similarity: 0.843:: Biden and Trump make competing trips to US border. The two likely presidential candidates make speeches in an effort to show they can tackle illegal crossings.
 Similarity: 0.836:: 'A reality show': World reacts to Trump-Biden debate . Global reviews were most scathing of Mr Biden, but his Republican challenger did not escape criticism.
 Similarity: 0.836:: Biden and Trump agree two debates as RFK cries foul. There will be no live audience at June's Atlanta event, which will mark the pair's first on-stage clash in four years.


Query: Best Marvel movie this year
 Similarity: 0.791:: Marvel star Jeremy Renner: I'm so blessed a year after accident. The Marvel star reflects on his recovery after being run over by his own snow plough last New Year's Day.
 Similarity: 0.773:: Tom Holland's Romeo wows crowds more than critics. Reviews describe the Spider-Man star's performance on stage as "good", "fine" and "perfectly OK".
 Similarity: 0.772:: Oscars 2024: Poor Things and Anatomy of a Fall scoop early awards. Best picture favourite Oppenheimer has 13 nominations and could become one of the biggest winners of all time.
 Similarity: 0.771:: Marvel star Karen Gillan is not scared of being cancelled . Scots actress Karen Gillan's new role made her face up to the pitfalls of social media.
 Similarity: 0.770:: Oppenheimer's Cillian Murphy and Robert Downey Jr scoop Bafta Film Awards. Cillian Murphy, Robert Downey Jr and Christopher Nolan all win Bafta Film Awards for Oppenheimer.
 Similarity: 0.768:: Oscars 2024: Everything you need to know ahead of big night of awards. As Hollywood's finest get ready for the big night, we bring you the lowdown on what to look out for.
 Similarity: 0.767:: The full list of Oscar winners - updating live. See who has won and been nominated for this year's coveted Academy Awards.
 Similarity: 0.767:: Bafta nominations 2024: The full list of film contenders. Oppenheimer and Poor Things are the leading contenders for this year's British Academy Film Awards.
 Similarity: 0.765:: 'The Valhalla nail-biter that had everything'. Xander Schauffele’s thrilling breakthrough PGA victory over Bryson DeChambeau portrayed major golf in the best possible light, writes Iain Carter.
 Similarity: 0.765:: The highs, lows and why Swift won. The best (and worst) performances, the memorable moments, and why Swift's big win was inevitable.


Query: Northern Lights
 Similarity: 0.853:: Why you probably missed the Northern Lights on Saturday. The Northern Lights waned early on Saturday night, but picked up again much later.
 Similarity: 0.851:: More Northern Lights soon as Sun storms strengthen. Another spectacular light show could come within two weeks as Sun storms reach 11-year high.
 Similarity: 0.850:: In pictures: Northern Lights dazzle around the world. The aurora borealis was visible around the world on Friday night, stunning photographers everywhere.
 Similarity: 0.848:: Northern lights give spectacular surprise display across UK. In a sudden display the aurora was seen from the Highlands down to Cornwall on Sunday night.
 Similarity: 0.846:: Watch: Northern Lights captured glowing over volcano. Volcanic eruptions have been taking place in the region since 14 January.
 Similarity: 0.840:: Northern Lights in dazzling display across the UK. A solar storm of this scale can cause disruptions to infrastructure such as the power grid.

In [5]:
from sklearn.metrics.pairwise import cosine_similarity

# Helper function to get embeddings
def get_embeddings(text, model, tokenizer):
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True).to("cpu")
    with torch.no_grad():
        embeddings = model(**inputs).last_hidden_state.mean(dim=1).cpu().numpy()
    return embeddings

# Calculate pre-fine-tuning similarities
similarities_before = []
for index, row in test_df.iterrows():
    query_embedding = get_embeddings(row['query'], model, tokenizer)
    content_embedding = get_embeddings(row['news_content'], model, tokenizer)
    similarity = cosine_similarity(query_embedding, content_embedding)[0][0]
    similarities_before.append(similarity)

    # Print the progress
    if (index + 1) % 100 == 0:  # Adjust the modulus value to print more or less frequently
        percent_complete = ((index + 1) / len(test_df)) * 100
        print(f"Processed {percent_complete:.0f}% -> {index + 1} out of {len(test_df)} rows.")

# Store pre-fine-tuning similarities
test_df['similarity_before'] = similarities_before
test_df.to_csv('notebooks_data/generated_queries_with_similarity_before.csv', index=False)
print("Average Pre-Fine-Tuning Similarity:", sum(similarities_before) / len(similarities_before))

Processed 300% -> 900 out of 300 rows.
Processed 167% -> 500 out of 300 rows.
Processed 100% -> 300 out of 300 rows.
Processed 200% -> 600 out of 300 rows.
Processed 67% -> 200 out of 300 rows.
Processed 267% -> 800 out of 300 rows.
Average Pre-Fine-Tuning Similarity: 0.8498281

In [6]:
from torch.utils.data import Dataset, DataLoader

class QueryNewsDataset(Dataset):
    def __init__(self, df, tokenizer, max_length=128):
        self.queries = df['query'].tolist()
        self.news = df['news_content'].tolist()
        self.tokenizer = tokenizer
        self.max_length = max_length
    
    def __len__(self):
        return len(self.queries)
    
    def __getitem__(self, idx):
        query_text = self.queries[idx]
        news_text = self.news[idx]
        
        query_inputs = self.tokenizer(query_text, padding='max_length', truncation=True, max_length=self.max_length, return_tensors="pt")
        news_inputs = self.tokenizer(news_text, padding='max_length', truncation=True, max_length=self.max_length, return_tensors="pt")
        
        return {
            'query_input_ids': query_inputs['input_ids'].squeeze(0),
            'query_attention_mask': query_inputs['attention_mask'].squeeze(0),
            'news_input_ids': news_inputs['input_ids'].squeeze(0),
            'news_attention_mask': news_inputs['attention_mask'].squeeze(0)
        }

# Create DataLoader for fine-tuning
train_loader = DataLoader(QueryNewsDataset(test_df, tokenizer), batch_size=8, shuffle=True)




import torch
from torch.nn import functional as F
from transformers import AdamW

# Optimizer
optimizer = AdamW(model.parameters(), lr=2e-5)

# Custom similarity loss function
def similarity_loss(embedding1, embedding2):
    cos_sim = F.cosine_similarity(embedding1, embedding2)
    return 1 - cos_sim.mean()

# Fine-tuning loop with progress updates
model.train()
for epoch in range(3):  # Adjust the number of epochs as needed
    total_loss = 0
    for i, batch in enumerate(train_loader):
        optimizer.zero_grad()
        
        # Query embeddings
        query_embeddings = model(
            input_ids=batch['query_input_ids'],
            attention_mask=batch['query_attention_mask']
        ).last_hidden_state.mean(dim=1)
        
        # News content embeddings
        news_embeddings = model(
            input_ids=batch['news_input_ids'],
            attention_mask=batch['news_attention_mask']
        ).last_hidden_state.mean(dim=1)
        
        # Calculate similarity loss and optimize
        loss = similarity_loss(query_embeddings, news_embeddings)
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
        
        # Print progress within each epoch
        if (i + 1) % 10 == 0:
            percent_complete = ((i + 1) / len(train_loader)) * 100
            print(f"Epoch {epoch + 1} - Processed {percent_complete:.0f}% -> {i + 1} out of {len(train_loader)} batches.")

    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch + 1} completed with average loss: {avg_loss:.4f}")

/Users/who/projects/task1/venv/lib/python3.11/site-packages/transformers/optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(

Epoch 1 - Processed 26% -> 10 out of 38 batches.
Epoch 1 - Processed 53% -> 20 out of 38 batches.
Epoch 1 - Processed 79% -> 30 out of 38 batches.
Epoch 1 completed with average loss: 0.1364
Epoch 2 - Processed 26% -> 10 out of 38 batches.
Epoch 2 - Processed 53% -> 20 out of 38 batches.
Epoch 2 - Processed 79% -> 30 out of 38 batches.
Epoch 2 completed with average loss: 0.1276
Epoch 3 - Processed 26% -> 10 out of 38 batches.
Epoch 3 - Processed 53% -> 20 out of 38 batches.
Epoch 3 - Processed 79% -> 30 out of 38 batches.
Epoch 3 completed with average loss: 0.1138

In [7]:
# Post-fine-tuning similarity calculation with progress updates
similarities_after = []
model.eval()
for i, row in test_df.iterrows():
    query_embedding = get_embeddings(row['query'], model, tokenizer)
    content_embedding = get_embeddings(row['news_content'], model, tokenizer)
    similarity = cosine_similarity(query_embedding, content_embedding)[0][0]
    similarities_after.append(similarity)
    
    # Print progress
    if (i + 1) % 100 == 0:
        percent_complete = ((i + 1) / len(test_df)) * 100
        print(f"Processed {percent_complete:.0f}% -> {i + 1} out of {len(test_df)} rows.")

test_df['similarity_after'] = similarities_after
print("Average Post-Fine-Tuning Similarity:", sum(similarities_after) / len(similarities_after))

# Display average similarity improvement
avg_similarity_before = test_df['similarity_before'].mean()
avg_similarity_after = test_df['similarity_after'].mean()
print(f"Average Similarity Before Fine-Tuning: {avg_similarity_before:.4f}")
print(f"Average Similarity After Fine-Tuning: {avg_similarity_after:.4f}")
print(f"Improvement: {avg_similarity_after - avg_similarity_before:.4f}")


test_queries = ["Products for Color-blind people","JEEP off-road vehicles","What is the origin of Bamba snack","Recommended diet and exercise habits for managing obesity","Keep your children safe on the internet","What are the lates news about AI ethics?","How the war between Israel and Hamas is affecting global politics?","Latest trends in the fashion industry","Interest rates","biden vs trump","Best Marvel movie this year","Northern Lights"]
for user_query in test_queries:
    print(f"\n\nQuery: {user_query}")
    top_news = find_top_news(user_query, df, model, tokenizer)
    for _, row in top_news.iterrows():
                print(f"\033[96m Similarity: {row['e5_similarity']:.3f}::\033[0m {row['content']}")

Processed 300% -> 900 out of 300 rows.
Processed 167% -> 500 out of 300 rows.
Processed 100% -> 300 out of 300 rows.
Processed 200% -> 600 out of 300 rows.
Processed 67% -> 200 out of 300 rows.
Processed 267% -> 800 out of 300 rows.
Average Post-Fine-Tuning Similarity: 0.8846712
Average Similarity Before Fine-Tuning: 0.8498
Average Similarity After Fine-Tuning: 0.8847
Improvement: 0.0348


Query: Products for Color-blind people
 Similarity: 0.801:: Cost of living: How can I make extra income?. Some people have been earning thousands selling clothes and other items since they were in school.
 Similarity: 0.798:: Ethnic bias in health devices 'puts patients at risk'. The review focuses on devices frequently used in the NHS, like pulse oximeters and skin cancer apps.
 Similarity: 0.793:: Electioncast: Laura Kuenssberg and Adam Fleming answer your questions. Adam and Laura answer your election questions
 Similarity: 0.791:: Aphantasia: Why I cannot see my children in my mind. Not everyone can picture images in their mind's eye and remember sounds or faces - but why?
 Similarity: 0.791:: Americanswers! What is Project 2025? Will Biden take a cognitive test?. We answer your questions on the biggest issues in the run-up to the election
 Similarity: 0.791:: Who can I vote for in the general election?. Find out which constituency you are in, who you can vote for and where you can vote using our postcode search.
 Similarity: 0.790:: 'I’ve invented an alternative to uncomfortable smear tests'. Sânziana Foia's non-invasive test detects harmful virus strains and delivers fast results at home.
 Similarity: 0.789:: Musician with hearing loss makes music from nature. A musician who lost her hearing overnight says it spurred her on to make new music from nature.
 Similarity: 0.788:: What are the parties saying about housing? - Your questions. Our cost of living correspondent answers your questions about housing and personal finance.
 Similarity: 0.788:: What is behind the TikTok thirst for Stanley water cups?. People are camping outside supermarkets in the US to try to buy the latest internet on-trend item.


Query: JEEP off-road vehicles
 Similarity: 0.785:: How to drive in icy weather. Tips on what to carry in your car, and how to drive in snow and icy weather.
 Similarity: 0.762:: Collapsing cliffs and washed-out roads after California storms. Days of heavy rainfall in California have caused flooding and mudslides, leaving infrastructure damaged.
 Similarity: 0.761:: Adults and teens turn to 'dumbphones'  to cut screen time. Parents and teens alike are trading in their smartphones for "dumber" models to help stay offline.
 Similarity: 0.761:: TV star shaken after Jaguar brakes fail during drive. Craig Phillips describes "terrifying feeling" when brakes failed on his Jaguar I-Pace
 Similarity: 0.760:: Our Range Rovers are not UK's most-stolen car, says Jaguar Land Rover. The boss of Jaguar Land Rover hits out at what he says is inaccurate reporting about the Range Rover.
 Similarity: 0.760:: Watch: Wheelie bins fly and a caravan overturns in wind. Cars are damaged and houses shake as a suspected tornado strikes in Knutton, Staffordshire.
 Similarity: 0.759:: California: Rockslide blocking road cleared with explosives. Video shared by Placer County shows a road completely blocked by boulders, that are then blasted into small pieces.
 Similarity: 0.757:: Have the wheels come off for Tesla?. As the electric carmaker sees sales fall and cuts jobs, we take a closer look at its problems.
 Similarity: 0.757:: XL Bully Ban, What Next?. Jordan Davies explores why the ban on the American XL bully dog is controversial.
 Similarity: 0.757:: UAE: A hailstorm in the desert? Rare weather phenomenon shocks residents. Large hailstones covered roads as a rare weather phenomenon hit the United Arab Emirates.


Query: What is the origin of Bamba snack
 Similarity: 0.781:: The Birmingham child who paved the way for the heel prick test. Sheila Jones, who had Phenylketonuria (PKU), was treated by pioneering doctors 70 years ago.
 Similarity: 0.779:: Nigeria's love-hate relationship with twins. Two communities with different views about twins that meant the difference between life and death.
 Similarity: 0.779:: Scientists grow 'meaty' rice hybrid food for protein kick. A team in South Korea say they have cracked how to grow beef muscle and fat cells inside grains of rice.
 Similarity: 0.779:: Kamila Valieva claimed contaminated strawberry dessert behind positive test. Banned figure skater Kamila Valieva claimed her positive doping test may have been caused by a contaminated strawberry dessert.
 Similarity: 0.778:: Big Zuu cuts down on cooking and rap for Ramadan. The rapper and TV chef visited Mecca for the first time to explore his Muslim faith for a documentary.
 Similarity: 0.776:: Raisin found in toddler's nose after three-month mystery. Three-year-old Peyton Handley told her parents that she had a pain and would scratch around her nose.
 Similarity: 0.775:: Come Dine With Me winners part of drug import plot. Members of a gang to import cannabis were foiled after reports of a theft, police say.
 Similarity: 0.775:: What is behind the TikTok thirst for Stanley water cups?. People are camping outside supermarkets in the US to try to buy the latest internet on-trend item.
 Similarity: 0.775:: The real story behind Bohemian Rhapsody. The full story behind Queen's iconic song.
 Similarity: 0.774:: One Love: How Kingsley Ben-Adir became Bob Marley on the set of Barbie. The actor initially turned down the role, saying it was too risky. What changed his mind?


Query: Recommended diet and exercise habits for managing obesity
 Similarity: 0.844:: Weighing up diet drugs. Obesity jabs 'could reduce heart attack risk' says new study
 Similarity: 0.811:: Are we being tricked by our fitness trackers?. How accurate are fitness trackers?
 Similarity: 0.811:: How do I register to vote?. Here’s what you need to know about how you register to vote and when.
 Similarity: 0.805:: Post Christmas debt: Which bills should I pay first?. What help and options are available to people struggling with debt repayments?
 Similarity: 0.802:: How to drive in icy weather. Tips on what to carry in your car, and how to drive in snow and icy weather.
 Similarity: 0.799:: What can I do if I can't pay my energy bill?. If you're struggling to afford your gas and electricity bills, what options are available?
 Similarity: 0.797:: How to win an Oscar. The campaigning behind the Academy Awards
 Similarity: 0.797:: Dog attacks: What can you do to protect yourself?. The best course of action will vary depending on the situation, dog behaviour experts explain.
 Similarity: 0.796:: Everything you need to know about student loans. How do they work across the UK, what can I borrow and when do I have to start paying it back?
 Similarity: 0.796:: Who can I vote for in the general election?. Find out which constituency you are in, who you can vote for and where you can vote using our postcode search.


Query: Keep your children safe on the internet
 Similarity: 0.837:: Tame toxic algorithms to protect children, big tech told. Big tech companies will have to make changes to their algorithms to comply with new online safety laws.
 Similarity: 0.833:: Bereaved parents win online harm battle. Tech firms will have to hand over personal data of children whose death may be related to online harm.
 Similarity: 0.832:: Brianna Ghey's mother and Molly Russell's father join forces to combat online harm. Esther Ghey and Ian Russell want better protection for teenagers on social media.
 Similarity: 0.824:: Tech firms told to hide 'toxic' content from children. Social media firms like Instagram and TikTok will have to make changes to comply with new online safety laws.
 Similarity: 0.816:: Back-to-school illness advice offered to parents. Health officials explain when to keep your child at home and how to stop the spread of bugs.
 Similarity: 0.815:: Rochdale abuse scandal: Inside the team fighting child sexual exploitation. How are police and child protection experts trying to prevent a repeat of the Rochdale abuse scandal?
 Similarity: 0.813:: Meta tool to block nude images in teens' private messages. The move is designed to help stop teenagers receiving inappropriate pictures, even in encrypted chats
 Similarity: 0.810:: Police investigate virtual sex assault on girl's avatar. The incident in a virtual world reportedly left the under-16-year-old traumatised.
 Similarity: 0.808:: New law aims to protect devices from hackers. Speakers, fitness trackers and other internet-connected devices sold in the UK now have to meet new requirements.
 Similarity: 0.808:: Could Ofcom ban social media for under-18s?. A quick, simple guide to the new social media rules proposed by Ofcom


Query: What are the lates news about AI ethics?
 Similarity: 0.827:: CES 2024: AI pillows and toothbrushes - is it all getting a bit silly?. Companies are clamouring to present their products as AI-powered, but are their claims justified?
 Similarity: 0.827:: Concern rises over AI in adult entertainment. AI in adult entertainment could have negative effects on society and individuals, experts say.
 Similarity: 0.826:: AI and humanity’s future: chilling or thrilling?. Amol & Nick take on Stephen Fry’s challenge & look at what the future of AI might entail.
 Similarity: 0.825:: How AI is being used to prevent illegal fishing. Illegal fishing remains a huge global problem, but AI is now being used to tackle the issue.
 Similarity: 0.824:: New version of Chat-GPT can teach maths and flirt . OpenAI has unveiled a new, faster version of its generative AI tool, ChatGPT.
 Similarity: 0.822:: AI could 'supercharge' election disinformation, US tells the BBC. US Deputy Attorney General Lisa Monaco says the US wants tougher sentences for crimes involving AI.
 Similarity: 0.822:: How AI is helping to prevent future power cuts. Artificial intelligence software is being used to predict electricity demand and supply.
 Similarity: 0.821:: Urgent need for terrorism AI laws, warns think tank. The government should 'urgently consider' AI-specific legislation a think-tank says.
 Similarity: 0.820:: AI will not be the destroyer of jobs - Bank chief. Bank of England governor says AI has "great potential" as Lords report urges UK to embrace AI.
 Similarity: 0.818:: What happens when you think AI is lying about you?. BBC Tech Editor Zoe Kleinman tried to challenge the output of a chatbot - but all was not as it seemed.


Query: How the war between Israel and Hamas is affecting global politics?
 Similarity: 0.856:: Israel-Palestinian bitterness deepened by Hamas attack and war. Both Israelis and Palestinians believe the world does not understand their pain and suffering.
 Similarity: 0.855:: Chris Mason: How Gaza conflict is contorting UK politics. The Conservatives, Labour, and Parliament itself are finding themselves torn by the furious arguments provoked by the Israel-Gaza war.
 Similarity: 0.850:: Could the Israel-Gaza war cost Biden the election?. The President’s said he’s 'outraged' by aid worker killings
 Similarity: 0.845:: Jeremy Bowen: What ICC arrest warrants mean for Israel and Hamas. The Israeli and Hamas leaders are suspected of committing war crimes during the continuing war in Gaza.
 Similarity: 0.839:: Israel-Gaza war: Latest ceasefire talks not very promising - Qatar. Israel's PM Benjamin Netanyahu vows to carry on the war against Hamas regardless of international pressure.
 Similarity: 0.838:: Why have Israel and Iran attacked each other?. The long-running shadow war between the two countries has come into the open.
 Similarity: 0.837:: Lyse Doucet: Hamas leader's assassination sparks wider war fears. Lyse Doucet assesses if Hezbollah and Hamas will retaliate after Saleh al-Arouri was killed in Lebanon.
 Similarity: 0.836:: Jeremy Bowen: Obstacles to peace seem larger than ever. The risk of an all-out Middle East war is increasing as the crisis in Gaza grows ever more desperate.
 Similarity: 0.836:: No let-up for Gazans while world focused on Iran attacks. Fighting continues in Gaza, where a humanitarian crisis is overshadowed by the wider regional conflict.
 Similarity: 0.836:: 100 days since Hamas attacked Israel, triggering war in Gaza. Thousands of Israelis gathered in Tel Aviv to mark 100 days since the start of the unprecedented war against Hamas.


Query: Latest trends in the fashion industry
 Similarity: 0.819:: How Zendaya perfected 'method dressing'. Film stars have made fancy dress fashionable in their recent red carpet looks.
 Similarity: 0.806:: Champagne, caffeine and chaos: Fashion week descends on Paris. Louis Vuitton, Dior, Hermes, Rick Owens, Loewe, Kenzo and Dries Van Noten all introduce new collections in Paris.
 Similarity: 0.806:: Egg Freezing and Me. Inside the world of one of the fastest growing fertility treatments in the UK.
 Similarity: 0.802:: The new language changing the dating scene. If you WLTM a ND with a GSOH, you might struggle to locate one on a modern dating app.
 Similarity: 0.802:: Kuenssberg: Are the politics of climate change going out of fashion?. Debate is shifting to cost concerns as net zero targets fast approach, says Laura Kuenssberg.
 Similarity: 0.795:: The most eye-catching looks from the Met Gala so far. Lea Michelle, Zendaya and Gigi Hadid are among the stars walking the red carpet.
 Similarity: 0.795:: CES 2024: AI pillows and toothbrushes - is it all getting a bit silly?. Companies are clamouring to present their products as AI-powered, but are their claims justified?
 Similarity: 0.795:: Zendaya and Kim Kardashian stun on Met Gala red carpet. The celebrities are showing up for fashion's night of nights in New York City.
 Similarity: 0.794:: Stars take over Paris for sporty Vogue fashion show. Supermodels, singers and sports star took to the runway in Paris as Vogue turned a square into a runway.
 Similarity: 0.794:: Robot Ships. The revolution in shipping using 'ghost' vessels with hardly any crew on board.


Query: Interest rates
 Similarity: 0.847:: Interest rates expected to be held at 5.25%. Despite inflation falling to 2%, experts are expecting interest rates to be held at a 16-year high.
 Similarity: 0.847:: What are UK interest rates and when will they fall?. Bank of England interest rates affect the mortgage, loan and savings rates for millions of people.
 Similarity: 0.843:: Inflation and Covid set our savings back 10 years. Justin Williams is one of many whose savings have eroded and mortgage rates have increased.
 Similarity: 0.843:: When will UK interest rates come down?. Bank of England interest rates affect mortgage, loan and savings rates for millions of people.
 Similarity: 0.843:: How do interest rates affect me?. Bank of England interest rates have an impact on the mortgage, loan and savings rates for millions of people.
 Similarity: 0.838:: Mortgage lenders rapidly changing interest rates. HSBC, NatWest and Virgin Money are all increasing mortgage rates continuing a frantic start to the year.
 Similarity: 0.838:: Bank of England expected to hold interest rates. The Bank is widely expected to keep rates at 5.25% for now, but cut them later in the year.
 Similarity: 0.837:: Interest rate cuts 'on the way', says Bank boss. The Bank of England has kept the cost of borrowing at 5.25% for the fifth time in a row.
 Similarity: 0.833:: Interest rates won't fall due to 4% inflation, says Bank boss. Bank of England boss says the latest inflation figure "pretty much leaves us where we were".
 Similarity: 0.830:: Bank 'optimistic' as it edges closer to summer cut. Its comments came as UK interest rates were left unchanged at a 16-year high of 5.25%.


Query: biden vs trump
 Similarity: 0.867:: Super Tuesday: Everything Points to Trump vs Biden. Trump and Biden win almost every state in election season's biggest primary night.
 Similarity: 0.862:: Illegal migration, tax and abortion - fact checking Trump-Biden debate. BBC Verify looks into various claims made on stage by Donald Trump and Joe Biden.
 Similarity: 0.861:: Where Biden and Trump stand on key issues. How the two candidates' policies compare on the economy, immigration, abortion and other big issues.
 Similarity: 0.857:: What to watch for at Biden and Trump's first debate. The BBC's Sarah Smith looks at what's at stake for both men as they prove they're worth a second White House term.
 Similarity: 0.856:: Watch key moments from Biden and Trump's first debate. The pair threw insults and clashed on stage about the biggest issues American voters care about - here's what they said.
 Similarity: 0.854:: Biden faces high-stakes address to calm Democratic nerves. The president will seek to fight concerns over his age and contrast his term in office with Donald Trump's.
 Similarity: 0.853:: Big stakes and high tension as Biden-Trump debate looms. Thursday's debate between the two will be a reunion of sorts - although not exactly a friendly one.
 Similarity: 0.852:: Biden and Trump make competing trips to US border. The two likely presidential candidates make speeches in an effort to show they can tackle illegal crossings.
 Similarity: 0.847:: Biden says he's ready for election debate with Trump. US President says he is "happy" to face rival who claims he is ready "anytime, anywhere, anyplace".
 Similarity: 0.846:: 'A reality show': World reacts to Trump-Biden debate . Global reviews were most scathing of Mr Biden, but his Republican challenger did not escape criticism.


Query: Best Marvel movie this year
 Similarity: 0.806:: Marvel star Jeremy Renner: I'm so blessed a year after accident. The Marvel star reflects on his recovery after being run over by his own snow plough last New Year's Day.
 Similarity: 0.788:: Oscars 2024: Poor Things and Anatomy of a Fall scoop early awards. Best picture favourite Oppenheimer has 13 nominations and could become one of the biggest winners of all time.
 Similarity: 0.788:: Tom Holland's Romeo wows crowds more than critics. Reviews describe the Spider-Man star's performance on stage as "good", "fine" and "perfectly OK".
 Similarity: 0.785:: Oppenheimer's Cillian Murphy and Robert Downey Jr scoop Bafta Film Awards. Cillian Murphy, Robert Downey Jr and Christopher Nolan all win Bafta Film Awards for Oppenheimer.
 Similarity: 0.785:: Oscars 2024: Everything you need to know ahead of big night of awards. As Hollywood's finest get ready for the big night, we bring you the lowdown on what to look out for.
 Similarity: 0.784:: Marvel star Karen Gillan is not scared of being cancelled . Scots actress Karen Gillan's new role made her face up to the pitfalls of social media.
 Similarity: 0.782:: The highs, lows and why Swift won. The best (and worst) performances, the memorable moments, and why Swift's big win was inevitable.
 Similarity: 0.782:: Bafta nominations 2024: The full list of film contenders. Oppenheimer and Poor Things are the leading contenders for this year's British Academy Film Awards.
 Similarity: 0.781:: The full list of Oscar winners - updating live. See who has won and been nominated for this year's coveted Academy Awards.
 Similarity: 0.779:: Cillian Murphy wins best actor as Oppenheimer sweeps Oscars. Cillian Murphy is the first Irish-born winner of the best actor award for his role as J Robert Oppenheimer.


Query: Northern Lights
 Similarity: 0.864:: More Northern Lights soon as Sun storms strengthen. Another spectacular light show could come within two weeks as Sun storms reach 11-year high.
 Similarity: 0.863:: Why you probably missed the Northern Lights on Saturday. The Northern Lights waned early on Saturday night, but picked up again much later.
 Similarity: 0.861:: Northern lights give spectacular surprise display across UK. In a sudden display the aurora was seen from the Highlands down to Cornwall on Sunday night.

# Fine tuning Rank 16

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split

from pymongo import MongoClient
import pandas as pd

# MongoDB connection details
mongo_uri = "mongodb://localhost:27017/"
db_name = "task1"
collection_name = "bbc_news"

# Connect to MongoDB
client = MongoClient(mongo_uri)
db = client[db_name]
collection = db[collection_name]

documents = list(collection.find())
df = pd.DataFrame(documents)
client.close()

queries_df = pd.read_csv('notebooks_data/generated_queries.csv')

train_df, test_df = train_test_split(queries_df, test_size=0.3, random_state=42)
print(f"Training set size: {len(train_df)}")
print(f"Test set size: {len(test_df)}")

from transformers import AutoTokenizer, AutoModel
from peft import LoraConfig, get_peft_model

# Load tokenizer and model without quantization
model_name = "intfloat/e5-large-v2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)  # Standard loading, no quantization

# Define QLoRA configuration
lora_config = LoraConfig(
    r=16,               # Rank of the low-rank matrices
    lora_alpha=32,      # Scaling factor for LoRA updates
    target_modules=["key", "query", "value"],  # Adjust based on model structure if necessary
    lora_dropout=0.1,   # Dropout for LoRA layers
    bias="none"         # Exclude biases to focus on core layers
)

# Wrap the model with QLoRA
model = get_peft_model(model, lora_config)

Training set size: 1399
Test set size: 600

In [9]:
import torch

def get_embeddings(text, model, tokenizer):
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True).to("cpu")
    with torch.no_grad():
        embeddings = model(**inputs).last_hidden_state.mean(dim=1).cpu().numpy()
    return embeddings


from sklearn.metrics.pairwise import cosine_similarity

def find_top_news(query, df, model, tokenizer, top_k=10):
    query_embedding = get_embeddings(query, model, tokenizer)

    # Calculate cosine similarity between query and all news embeddings
    similarities = df['e5_embedding_before_tuning'].apply(lambda x: cosine_similarity(query_embedding, x)[0][0])
    
    # Add similarity scores to the DataFrame
    df['e5_similarity'] = similarities
    
    # Sort by similarity and return the top_k results
    top_matches = df.nlargest(top_k, 'e5_similarity')
    
    # Clean up by dropping the 'similarity' column
    df.drop(columns=['e5_similarity'], inplace=True)
    
    return top_matches[['content', 'e5_similarity']]

In [10]:
from torch.utils.data import Dataset, DataLoader

class QueryNewsDataset(Dataset):
    def __init__(self, df, tokenizer, max_length=128):
        self.queries = df['query'].tolist()
        self.news = df['news_content'].tolist()
        self.tokenizer = tokenizer
        self.max_length = max_length
    
    def __len__(self):
        return len(self.queries)
    
    def __getitem__(self, idx):
        query_text = self.queries[idx]
        news_text = self.news[idx]
        
        query_inputs = self.tokenizer(query_text, padding='max_length', truncation=True, max_length=self.max_length, return_tensors="pt")
        news_inputs = self.tokenizer(news_text, padding='max_length', truncation=True, max_length=self.max_length, return_tensors="pt")
        
        return {
            'query_input_ids': query_inputs['input_ids'].squeeze(0),
            'query_attention_mask': query_inputs['attention_mask'].squeeze(0),
            'news_input_ids': news_inputs['input_ids'].squeeze(0),
            'news_attention_mask': news_inputs['attention_mask'].squeeze(0)
        }

# Create DataLoader for fine-tuning
train_loader = DataLoader(QueryNewsDataset(test_df, tokenizer), batch_size=8, shuffle=True)




import torch
from torch.nn import functional as F
from transformers import AdamW

# Optimizer
optimizer = AdamW(model.parameters(), lr=2e-5)

# Custom similarity loss function
def similarity_loss(embedding1, embedding2):
    cos_sim = F.cosine_similarity(embedding1, embedding2)
    return 1 - cos_sim.mean()

# Fine-tuning loop with progress updates
model.train()
for epoch in range(3):  # Adjust the number of epochs as needed
    total_loss = 0
    for i, batch in enumerate(train_loader):
        optimizer.zero_grad()
        
        # Query embeddings
        query_embeddings = model(
            input_ids=batch['query_input_ids'],
            attention_mask=batch['query_attention_mask']
        ).last_hidden_state.mean(dim=1)
        
        # News content embeddings
        news_embeddings = model(
            input_ids=batch['news_input_ids'],
            attention_mask=batch['news_attention_mask']
        ).last_hidden_state.mean(dim=1)
        
        # Calculate similarity loss and optimize
        loss = similarity_loss(query_embeddings, news_embeddings)
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
        
        # Print progress within each epoch
        if (i + 1) % 10 == 0:
            percent_complete = ((i + 1) / len(train_loader)) * 100
            print(f"Epoch {epoch + 1} - Processed {percent_complete:.0f}% -> {i + 1} out of {len(train_loader)} batches.")

    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch + 1} completed with average loss: {avg_loss:.4f}")

/Users/who/projects/task1/venv/lib/python3.11/site-packages/transformers/optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(

Epoch 1 - Processed 13% -> 10 out of 75 batches.
Epoch 1 - Processed 27% -> 20 out of 75 batches.
Epoch 1 - Processed 40% -> 30 out of 75 batches.
Epoch 1 - Processed 53% -> 40 out of 75 batches.
Epoch 1 - Processed 67% -> 50 out of 75 batches.
Epoch 1 - Processed 80% -> 60 out of 75 batches.
Epoch 1 - Processed 93% -> 70 out of 75 batches.
Epoch 1 completed with average loss: 0.1149
Epoch 2 - Processed 13% -> 10 out of 75 batches.
Epoch 2 - Processed 27% -> 20 out of 75 batches.
Epoch 2 - Processed 40% -> 30 out of 75 batches.
Epoch 2 - Processed 53% -> 40 out of 75 batches.
Epoch 2 - Processed 67% -> 50 out of 75 batches.
Epoch 2 - Processed 80% -> 60 out of 75 batches.
Epoch 2 - Processed 93% -> 70 out of 75 batches.
Epoch 2 completed with average loss: 0.0459
Epoch 3 - Processed 13% -> 10 out of 75 batches.
Epoch 3 - Processed 27% -> 20 out of 75 batches.
Epoch 3 - Processed 40% -> 30 out of 75 batches.
Epoch 3 - Processed 53% -> 40 out of 75 batches.
Epoch 3 - Processed 67% -> 50 out of 75 batches.
Epoch 3 - Processed 80% -> 60 out of 75 batches.
Epoch 3 - Processed 93% -> 70 out of 75 batches.
Epoch 3 completed with average loss: 0.0093

In [12]:
# Post-fine-tuning similarity calculation with progress updates
similarities_after = []
model.eval()
for i, row in test_df.iterrows():
    query_embedding = get_embeddings(row['query'], model, tokenizer)
    content_embedding = get_embeddings(row['news_content'], model, tokenizer)
    similarity = cosine_similarity(query_embedding, content_embedding)[0][0]
    similarities_after.append(similarity)
    
    # Print progress
    if (i + 1) % 100 == 0:
        percent_complete = ((i + 1) / len(test_df)) * 100
        print(f"Processed {percent_complete:.0f}% -> {i + 1} out of {len(test_df)} rows.")

print("Average Post-Fine-Tuning Similarity:", sum(similarities_after) / len(similarities_after))

df['e5_embedding_before_tuning'] = df['content'].apply(lambda x: get_embeddings(x, model, tokenizer))

test_queries = ["Products for Color-blind people","JEEP off-road vehicles","What is the origin of Bamba snack","Recommended diet and exercise habits for managing obesity","Keep your children safe on the internet","What are the lates news about AI ethics?","How the war between Israel and Hamas is affecting global politics?","Latest trends in the fashion industry","Interest rates","biden vs trump","Best Marvel movie this year","Northern Lights"]
for user_query in test_queries:
    print(f"\n\nQuery: {user_query}")
    top_news = find_top_news(user_query, df, model, tokenizer)
    for _, row in top_news.iterrows():
                print(f"\033[96m Similarity: {row['e5_similarity']:.3f}::\033[0m {row['content']}")

Processed 300% -> 1800 out of 600 rows.
Processed 17% -> 100 out of 600 rows.
Processed 100% -> 600 out of 600 rows.
Processed 267% -> 1600 out of 600 rows.
Processed 33% -> 200 out of 600 rows.
Processed 217% -> 1300 out of 600 rows.
Processed 233% -> 1400 out of 600 rows.
Average Post-Fine-Tuning Similarity: 0.9971273


Query: Products for Color-blind people
 Similarity: 0.993:: Where workers are exploited to harvest an everyday ingredient. Brazilian workers face degrading conditions to harvest palm wax used in sweets, pills and lipstick.
 Similarity: 0.992:: Seven conditions that your local chemist can now treat. Pharmacies in England are able to supply antibiotics and advice without patients seeing a doctor.
 Similarity: 0.992:: A wine a mile: Marathon runner tastes 25 glasses. Tom Gilbey sampled 25 wines in a blind taste test challenge correctly identifying 21.
 Similarity: 0.992:: Removing large wine glasses from sale cuts drinking - study. With the largest measure off the menu, 7.6% less volume of wine was sold daily, researchers found.
 Similarity: 0.992:: The explosions of colour that painted a Glasgow estate. Sony’s 2006 “Paint” advert is widely considered one of the most ambitious in history - but how was it made?
 Similarity: 0.992:: Man's joy at Northern Lights and glowing plankton sea shots. Photographer Lee McGrath waited hours to capture the amazing phenomenon on the south Wales coast.
 Similarity: 0.992:: How portable X-ray machines are helping remote patients. Portable X-ray equipment that can take high quality images is transforming healthcare in remote areas.
 Similarity: 0.992:: Nail technicians join forces to raise prices. Nail technicians unite to raise their charges in what they call "National Nail Price Increase Day”.
 Similarity: 0.992:: See images of the Pink Moon spotted across the US. While the moon doesn't look particularly pink, it's named after pink flowers called wild ground phlox.
 Similarity: 0.992:: Apple Vision Pro: $3,499 headset finally gets release date. Apple's long-awaited mixed-reality headset will launch in the US on 2 February.


Query: JEEP off-road vehicles
 Similarity: 0.991:: How to drive in icy weather. Tips on what to carry in your car, and how to drive in snow and icy weather.
 Similarity: 0.991:: UAE: A hailstorm in the desert? Rare weather phenomenon shocks residents. Large hailstones covered roads as a rare weather phenomenon hit the United Arab Emirates.
 Similarity: 0.991:: Ingenuity: Damage puts end to ground-breaking Mars helicopter mission. The first vehicle to achieve powered flight on another planet suffers rotor damage three years into tour.
 Similarity: 0.991:: Watch: Tesla Norway fjord crash passengers saved by floating sauna users. The users of a sauna boat came to the rescue of two people who crashed into a fjord in Oslo.
 Similarity: 0.991:: Watch: Wheelie bins fly and a caravan overturns in wind. Cars are damaged and houses shake as a suspected tornado strikes in Knutton, Staffordshire.
 Similarity: 0.991:: Car slides on roof after drink-driver crash. Dashcam footage shows the car sliding along the carriageway with sparks flying out from underneath.
 Similarity: 0.991:: Six skiers missing near Matterhorn in Swiss Alps. The Swiss Alps have seen high winds for some days, and over the last 24 hours, heavy snowfalls.
 Similarity: 0.991:: Mystery monolith appears in Nevada desert. The Nevada monolith is one of number of similar structures have been found around the world in recent years.
 Similarity: 0.991:: Giraffe Benito escapes extreme temperatures for new home. A giraffe is being moved 2,000km south from Ciudad Juárez in northern Mexico to more temperate climes.
 Similarity: 0.991:: Driver eating McDonald's seen with hands off wheel. National Highways shares video of three dangerous driving incidents to coincide with a safety initiative.


Query: What is the origin of Bamba snack
 Similarity: 0.994:: Scientists grow 'meaty' rice hybrid food for protein kick. A team in South Korea say they have cracked how to grow beef muscle and fat cells inside grains of rice.
 Similarity: 0.994:: Big Zuu cuts down on cooking and rap for Ramadan. The rapper and TV chef visited Mecca for the first time to explore his Muslim faith for a documentary.
 Similarity: 0.994:: Australian farm grows world's biggest blueberry. The monster fruit is the size of a ping-pong ball and weighs 20.4g, about 10 times the average blueberry.
 Similarity: 0.994:: Jennifer Lopez plans to produce Bob the Builder film set in Puerto Rico. The news comes hot on the heels of the box office success of another Mattel character, Barbie.
 Similarity: 0.993:: Moti Mahal: India curry houses battle over butter chicken. Butter chicken - a curry popular around the world - is now in the middle of a court battle in India.
 Similarity: 0.993:: Gregg Wallace and the celebrities who have overshared their daily routines. Masterchef judge Gregg Wallace went viral this week after revealing a breakdown of his typical day.
 Similarity: 0.993:: Hyena shocks Kenyan after sneaking into his shop. Fredrick Omungu opened his business in the morning to discover the animal hiding under the counter.
 Similarity: 0.993:: Celebrating the legacy of Bob Marley. Trevor Nelson presents an orchestral reimagining of Bob Marley’s greatest hits.
 Similarity: 0.993:: The woman who spent Christmas in search of a rare plant. 'Nature hero' Rosemary Parslow is still helping the wildlife of the Scilly Isles even in her late 80s.
 Similarity: 0.993:: First product of Meghan's lifestyle brand revealed. The jars of strawberry jam, labelled America Riviera Orchard, have been shared with friends and influencers.


Query: Recommended diet and exercise habits for managing obesity
 Similarity: 0.995:: Weighing up diet drugs. Obesity jabs 'could reduce heart attack risk' says new study
 Similarity: 0.994:: Katie Price low calorie diet advert banned. The social media post irresponsibly promoted a diet that fell below 800 calories a day, a watchdog says.
 Similarity: 0.994:: Why choosing whole grains can benefit our health. Why choosing whole grains can help your heart, your microbiome and your blood sugar.
 Similarity: 0.993:: Did bodybuilding bring on my early perimenopause?. Adele Johnston was 33 when she developed painful symptoms such as heart palpitations and itchy skin.
 Similarity: 0.993:: Doctors question science behind blood sugar diet trend. Experts say there is "no strong evidence" the monitors, proven to be effective in managing diabetes, can also help people without the condition.
 Similarity: 0.993:: Global alert issued over fake Ozempic drugs - WHO. The World Health Organization says fake drugs, used for type-2 diabetes and weight loss, are a danger to health.
 Similarity: 0.993:: Wegovy, the 'Viagra' of weight-loss drugs flying off the shelves. How did Danish weight-loss treatment Wegovy become a global sales sensation?
 Similarity: 0.993:: May horrified to learn about risks of diabetes disordered eating. Better awareness and more NHS support are needed, the former prime minister says.
 Similarity: 0.993:: Scientists grow 'meaty' rice hybrid food for protein kick. A team in South Korea say they have cracked how to grow beef muscle and fat cells inside grains of rice.
 Similarity: 0.993:: Blood test reveals best lung cancer treatment. Test for patients in England checks if tumours can be treated with pills rather than chemotherapy.


Query: Keep your children safe on the internet
 Similarity: 0.994:: Bereaved parents win online harm battle. Tech firms will have to hand over personal data of children whose death may be related to online harm.
 Similarity: 0.993:: Brianna Ghey's mother and Molly Russell's father join forces to combat online harm. Esther Ghey and Ian Russell want better protection for teenagers on social media.
 Similarity: 0.993:: Meta tool to block nude images in teens' private messages. The move is designed to help stop teenagers receiving inappropriate pictures, even in encrypted chats
 Similarity: 0.993:: Back-to-school illness advice offered to parents. Health officials explain when to keep your child at home and how to stop the spread of bugs.
 Similarity: 0.993:: US health chief wants smoking-style warning labels on social media. Vivek Murthy says social media increases the risk that children will experience anxiety and depression.
 Similarity: 0.993:: Tech firms told to hide 'toxic' content from children. Social media firms like Instagram and TikTok will have to make changes to comply with new online safety laws.
 Similarity: 0.993:: Adults and teens turn to 'dumbphones'  to cut screen time. Parents and teens alike are trading in their smartphones for "dumber" models to help stay offline.
 Similarity: 0.993:: Tame toxic algorithms to protect children, big tech told. Big tech companies will have to make changes to their algorithms to comply with new online safety laws.
 Similarity: 0.993:: Teenagers accused in half of child abuse cases. Young people are unaware taking and sharing nude pictures of someone under 18 is a crime, police say.
 Similarity: 0.992:: Pupils get rare alert over dangers of sextortion. The National Crime Agency says young boys are increasingly being targeted by gangs.


Query: What are the lates news about AI ethics?
 Similarity: 0.997:: AI and humanity’s future: chilling or thrilling?. Amol & Nick take on Stephen Fry’s challenge & look at what the future of AI might entail.
 Similarity: 0.996:: AI could 'supercharge' election disinformation, US tells the BBC. US Deputy Attorney General Lisa Monaco says the US wants tougher sentences for crimes involving AI.
 Similarity: 0.996:: What happens when you think AI is lying about you?. BBC Tech Editor Zoe Kleinman tried to challenge the output of a chatbot - but all was not as it seemed.
 Similarity: 0.996:: How AI is being used to prevent illegal fishing. Illegal fishing remains a huge global problem, but AI is now being used to tackle the issue.
 Similarity: 0.996:: CES 2024: AI pillows and toothbrushes - is it all getting a bit silly?. Companies are clamouring to present their products as AI-powered, but are their claims justified?
 Similarity: 0.996:: Have we lost faith in technology?. The BBC's technology editor Zoe Kleinman looks at the technology sector's damaged reputation.
 Similarity: 0.996:: Urgent need for terrorism AI laws, warns think tank. The government should 'urgently consider' AI-specific legislation a think-tank says.
 Similarity: 0.996:: More people turning away from news, report says. News avoidance is now at record high levels, the Reuters Institute's 2024 Digital News Report says.
 Similarity: 0.996:: Facebook and Instagram to label all fake AI images. The tech will detect images - but not video or audio - made by other companies' AI generators.
 Similarity: 0.996:: AI will not be the destroyer of jobs - Bank chief. Bank of England governor says AI has "great potential" as Lords report urges UK to embrace AI.


Query: How the war between Israel and Hamas is affecting global politics?
 Similarity: 0.998:: Why have Israel and Iran attacked each other?. The long-running shadow war between the two countries has come into the open.
 Similarity: 0.998:: Chris Mason: How Gaza conflict is contorting UK politics. The Conservatives, Labour, and Parliament itself are finding themselves torn by the furious arguments provoked by the Israel-Gaza war.
 Similarity: 0.997:: Bowen: As Israel debates Iran attack response, can US and allies stop slide into all-out war?. World leaders are scrambling to prevent the Middle East entering a damaging wider conflict.
 Similarity: 0.997:: Jeremy Bowen: The Israel-Gaza war is at a crossroads. Will the killing of foreign aid workers exhaust the patience of Israel's allies?
 Similarity: 0.997:: 'We are surrounded' - Guarding the Middle East's most dangerous border. Clashes between Israel and Hezbollah are intensifying as the risk of a wider regional conflict grows.
 Similarity: 0.997:: Israel-Gaza war: Latest ceasefire talks not very promising - Qatar. Israel's PM Benjamin Netanyahu vows to carry on the war against Hamas regardless of international pressure.
 Similarity: 0.997:: Have Iran-Israel missile strikes changed the Middle East?. Political and military leaders are still absorbing the extraordinary exchange of fire, writes James Landale.
 Similarity: 0.997:: Was this the week Israel and Hezbollah drew closer to war?. Israel may be fighting in Gaza, but fear remains a war with Hezbollah could turn the conflict into something even deadlier.
 Similarity: 0.997:: Israeli minister attacks Netanyahu over Gaza future. There are growing signs of divisions within Israel's war cabinet over who should gover Gaza after the war.
 Similarity: 0.997:: Jeremy Bowen: What ICC arrest warrants mean for Israel and Hamas. The Israeli and Hamas leaders are suspected of committing war crimes during the continuing war in Gaza.


Query: Latest trends in the fashion industry
 Similarity: 0.994:: How Zendaya perfected 'method dressing'. Film stars have made fancy dress fashionable in their recent red carpet looks.
 Similarity: 0.993:: London Fashion Week: Celebrating 40 years of catwalks. As London Fashion Week marks four decades of creativity, we look back at some memorable moments.
 Similarity: 0.993:: The most eye-catching looks from the Met Gala so far. Lea Michelle, Zendaya and Gigi Hadid are among the stars walking the red carpet.
 Similarity: 0.993:: Stars take over Paris for sporty Vogue fashion show. Supermodels, singers and sports star took to the runway in Paris as Vogue turned a square into a runway.
 Similarity: 0.993:: Vinted makes first profit on used fashion. The second-hand fashion marketplace is the first of the new "pre-loved" clothing platforms to make a profit.
 Similarity: 0.993:: Grammy Awards 2024: Red carpet and ceremony in pictures. See the most eye-catching images and outfits as stars attend the music industry's biggest party.
 Similarity: 0.993:: In pictures: London Fashion Week's big moments. A surprise appearance from the supermodel topped off the 40th anniversary celebrations.
 Similarity: 0.993:: In pictures:  Daisy's hot pants and other striking outfits from the red carpet. Big names from films like Barbie, Oppenheimer and Saltburn step out at the British awards ceremony.
 Similarity: 0.993:: Champagne, caffeine and chaos: Fashion week descends on Paris. Louis Vuitton, Dior, Hermes, Rick Owens, Loewe, Kenzo and Dries Van Noten all introduce new collections in Paris.
 Similarity: 0.993:: The outfits: Stars turn on the style for the Oscars. The fashion is as important as the films at the glittering Hollywood award ceremony.


Query: Interest rates
 Similarity: 0.994:: How do interest rates affect me?. Bank of England interest rates have an impact on the mortgage, loan and savings rates for millions of people.
 Similarity: 0.994:: Interest rates expected to be held at 5.25%. Despite inflation falling to 2%, experts are expecting interest rates to be held at a 16-year high.
 Similarity: 0.994:: When will UK interest rates come down?. Bank of England interest rates affect mortgage, loan and savings rates for millions of people.
 Similarity: 0.994:: What are UK interest rates and when will they fall?. Bank of England interest rates affect the mortgage, loan and savings rates for millions of people.
 Similarity: 0.993:: Bank of England expected to hold interest rates. The Bank is widely expected to keep rates at 5.25% for now, but cut them later in the year.
 Similarity: 0.993:: Bank opens door for August interest rate cut. The Bank of England keeps borrowing costs unchanged, but hints it could cut rates later in the summer.
 Similarity: 0.993:: Mortgage lenders rapidly changing interest rates. HSBC, NatWest and Virgin Money are all increasing mortgage rates continuing a frantic start to the year.
 Similarity: 0.993:: Homeowner pain as major banks hike mortgage rates. Lenders respond over views the Bank of England may not cut interest rates as soon as previously thought.
 Similarity: 0.993:: Interest rate cuts 'on the way', says Bank boss. The Bank of England has kept the cost of borrowing at 5.25% for the fifth time in a row.
 Similarity: 0.993:: Bank of England expected to hold rates at 5.25%. Some economists expect hints about possible rate cuts later this year.


Query: biden vs trump
 Similarity: 0.994:: Super Tuesday: Everything Points to Trump vs Biden. Trump and Biden win almost every state in election season's biggest primary night.
 Similarity: 0.994:: Where Biden and Trump stand on key issues. How the two candidates' policies compare on the economy, immigration, abortion and other big issues.
 Similarity: 0.993:: Biden and Trump make competing trips to US border. The two likely presidential candidates make speeches in an effort to show they can tackle illegal crossings.
 Similarity: 0.993:: Biden says he's ready for election debate with Trump. US President says he is "happy" to face rival who claims he is ready "anytime, anywhere, anyplace".
 Similarity: 0.993:: What to watch for at Biden and Trump's first debate. The BBC's Sarah Smith looks at what's at stake for both men as they prove they're worth a second White House term.
 Similarity: 0.993:: Illegal migration, tax and abortion - fact checking Trump-Biden debate. BBC Verify looks into various claims made on stage by Donald Trump and Joe Biden.
 Similarity: 0.993:: Trump posts video of truck showing hog-tied Biden. The Biden campaign condemns the video, accusing Donald Trump of "regularly inciting political violence".
 Similarity: 0.993:: Big stakes and high tension as Biden-Trump debate looms. Thursday's debate between the two will be a reunion of sorts - although not exactly a friendly one.
 Similarity: 0.993:: 'A reality show': World reacts to Trump-Biden debate . Global reviews were most scathing of Mr Biden, but his Republican challenger did not escape criticism.
 Similarity: 0.993:: Biden faces high-stakes address to calm Democratic nerves. The president will seek to fight concerns over his age and contrast his term in office with Donald Trump's.


Query: Best Marvel movie this year
 Similarity: 0.992:: Oppenheimer: Cillian Murphy film marches towards Oscars success. Christopher Nolan's film got another boost in its awards campaign at last week's Golden Globes.
 Similarity: 0.992:: Oppenheimer among Bafta best film nominees. Barbie was the top grossing film of 2023 and received great reviews, but missed out on a best film nomination.
 Similarity: 0.991:: Bafta nominations 2024: The full list of film contenders. Oppenheimer and Poor Things are the leading contenders for this year's British Academy Film Awards.
 Similarity: 0.991:: Oscars 2024: Poor Things and Anatomy of a Fall scoop early awards. Best picture favourite Oppenheimer has 13 nominations and could become one of the biggest winners of all time.
 Similarity: 0.991:: Oppenheimer's Cillian Murphy and Robert Downey Jr scoop Bafta Film Awards. Cillian Murphy, Robert Downey Jr and Christopher Nolan all win Bafta Film Awards for Oppenheimer.
 Similarity: 0.991:: All you need to know for tonight's Bafta Games Awards. Zelda, Baldur's Gate 3 and Spider-Man 2 are among the frontrunners at this year's ceremony.
 Similarity: 0.991:: Moana: Disney's hit animation to get surprise cinema sequel this year. Disney's unexpected announcement sets up a box office battle with the first Wicked film.
 Similarity: 0.991:: Jamie Dornan 'hid' after reviews of Fifty Shades film. The 2015 film was popular with fans and a box office hit but was critically panned.
 Similarity: 0.991:: Which films are the favourites for the Oscars?. Three films are expected to dominate the Oscars after the nominations were announced for the 96th Academy awards.

# 1K rank 4 alpha 16

In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split

from pymongo import MongoClient
import pandas as pd

# MongoDB connection details
mongo_uri = "mongodb://localhost:27017/"
db_name = "task1"
collection_name = "bbc_news"

# Connect to MongoDB
client = MongoClient(mongo_uri)
db = client[db_name]
collection = db[collection_name]

documents = list(collection.find())
df = pd.DataFrame(documents)
client.close()

queries_df = pd.read_csv('notebooks_data/generated_queries.csv')
queries_df = queries_df.iloc[:1000]

train_df, test_df = train_test_split(queries_df, test_size=0.3, random_state=42)
print(f"Training set size: {len(train_df)}")
print(f"Test set size: {len(test_df)}")

from transformers import AutoTokenizer, AutoModel
from peft import LoraConfig, get_peft_model

# Load tokenizer and model without quantization
model_name = "intfloat/e5-large-v2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)  # Standard loading, no quantization

# Define QLoRA configuration
lora_config = LoraConfig(
    r=4,               # Rank of the low-rank matrices
    lora_alpha=16,      # Scaling factor for LoRA updates
    target_modules=["key", "query", "value"],  # Adjust based on model structure if necessary
    lora_dropout=0.1,   # Dropout for LoRA layers
    bias="none"         # Exclude biases to focus on core layers
)

# Wrap the model with QLoRA
model = get_peft_model(model, lora_config)

Training set size: 700
Test set size: 300

In [17]:
import torch

def get_embeddings(text, model, tokenizer):
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True).to("cpu")
    with torch.no_grad():
        embeddings = model(**inputs).last_hidden_state.mean(dim=1).cpu().numpy()
    return embeddings


from sklearn.metrics.pairwise import cosine_similarity

def find_top_news(query, df, model, tokenizer, top_k=10):
    query_embedding = get_embeddings(query, model, tokenizer)

    # Calculate cosine similarity between query and all news embeddings
    similarities = df['e5_embedding_before_tuning'].apply(lambda x: cosine_similarity(query_embedding, x)[0][0])
    
    # Add similarity scores to the DataFrame
    df['e5_similarity'] = similarities
    
    # Sort by similarity and return the top_k results
    top_matches = df.nlargest(top_k, 'e5_similarity')
    
    # Clean up by dropping the 'similarity' column
    df.drop(columns=['e5_similarity'], inplace=True)
    
    return top_matches[['content', 'e5_similarity']]

In [18]:
from torch.utils.data import Dataset, DataLoader

class QueryNewsDataset(Dataset):
    def __init__(self, df, tokenizer, max_length=128):
        self.queries = df['query'].tolist()
        self.news = df['news_content'].tolist()
        self.tokenizer = tokenizer
        self.max_length = max_length
    
    def __len__(self):
        return len(self.queries)
    
    def __getitem__(self, idx):
        query_text = self.queries[idx]
        news_text = self.news[idx]
        
        query_inputs = self.tokenizer(query_text, padding='max_length', truncation=True, max_length=self.max_length, return_tensors="pt")
        news_inputs = self.tokenizer(news_text, padding='max_length', truncation=True, max_length=self.max_length, return_tensors="pt")
        
        return {
            'query_input_ids': query_inputs['input_ids'].squeeze(0),
            'query_attention_mask': query_inputs['attention_mask'].squeeze(0),
            'news_input_ids': news_inputs['input_ids'].squeeze(0),
            'news_attention_mask': news_inputs['attention_mask'].squeeze(0)
        }

# Create DataLoader for fine-tuning
train_loader = DataLoader(QueryNewsDataset(test_df, tokenizer), batch_size=8, shuffle=True)




import torch
from torch.nn import functional as F
from transformers import AdamW

# Optimizer
optimizer = AdamW(model.parameters(), lr=2e-5)

# Custom similarity loss function
def similarity_loss(embedding1, embedding2):
    cos_sim = F.cosine_similarity(embedding1, embedding2)
    return 1 - cos_sim.mean()

# Fine-tuning loop with progress updates
model.train()
for epoch in range(3):  # Adjust the number of epochs as needed
    total_loss = 0
    for i, batch in enumerate(train_loader):
        optimizer.zero_grad()
        
        # Query embeddings
        query_embeddings = model(
            input_ids=batch['query_input_ids'],
            attention_mask=batch['query_attention_mask']
        ).last_hidden_state.mean(dim=1)
        
        # News content embeddings
        news_embeddings = model(
            input_ids=batch['news_input_ids'],
            attention_mask=batch['news_attention_mask']
        ).last_hidden_state.mean(dim=1)
        
        # Calculate similarity loss and optimize
        loss = similarity_loss(query_embeddings, news_embeddings)
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
        
        # Print progress within each epoch
        if (i + 1) % 10 == 0:
            percent_complete = ((i + 1) / len(train_loader)) * 100
            print(f"Epoch {epoch + 1} - Processed {percent_complete:.0f}% -> {i + 1} out of {len(train_loader)} batches.")

    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch + 1} completed with average loss: {avg_loss:.4f}")

/Users/who/projects/task1/venv/lib/python3.11/site-packages/transformers/optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(

Epoch 1 - Processed 26% -> 10 out of 38 batches.
Epoch 1 - Processed 53% -> 20 out of 38 batches.
Epoch 1 - Processed 79% -> 30 out of 38 batches.
Epoch 1 completed with average loss: 0.1322
Epoch 2 - Processed 26% -> 10 out of 38 batches.
Epoch 2 - Processed 53% -> 20 out of 38 batches.
Epoch 2 - Processed 79% -> 30 out of 38 batches.
Epoch 2 completed with average loss: 0.1128
Epoch 3 - Processed 26% -> 10 out of 38 batches.
Epoch 3 - Processed 53% -> 20 out of 38 batches.
Epoch 3 - Processed 79% -> 30 out of 38 batches.
Epoch 3 completed with average loss: 0.0849

In [19]:
# Post-fine-tuning similarity calculation with progress updates
similarities_after = []
model.eval()
for i, row in test_df.iterrows():
    query_embedding = get_embeddings(row['query'], model, tokenizer)
    content_embedding = get_embeddings(row['news_content'], model, tokenizer)
    similarity = cosine_similarity(query_embedding, content_embedding)[0][0]
    similarities_after.append(similarity)
    
    # Print progress
    if (i + 1) % 100 == 0:
        percent_complete = ((i + 1) / len(test_df)) * 100
        print(f"Processed {percent_complete:.0f}% -> {i + 1} out of {len(test_df)} rows.")

print("Average Post-Fine-Tuning Similarity:", sum(similarities_after) / len(similarities_after))

df['e5_embedding_before_tuning'] = df['content'].apply(lambda x: get_embeddings(x, model, tokenizer))

test_queries = ["Products for Color-blind people","JEEP off-road vehicles","What is the origin of Bamba snack","Recommended diet and exercise habits for managing obesity","Keep your children safe on the internet","What are the lates news about AI ethics?","How the war between Israel and Hamas is affecting global politics?","Latest trends in the fashion industry","Interest rates","biden vs trump","Best Marvel movie this year","Northern Lights"]
for user_query in test_queries:
    print(f"\n\nQuery: {user_query}")
    top_news = find_top_news(user_query, df, model, tokenizer)
    for _, row in top_news.iterrows():
                print(f"\033[96m Similarity: {row['e5_similarity']:.3f}::\033[0m {row['content']}")

Processed 300% -> 900 out of 300 rows.
Processed 167% -> 500 out of 300 rows.
Processed 100% -> 300 out of 300 rows.
Processed 200% -> 600 out of 300 rows.
Processed 67% -> 200 out of 300 rows.
Processed 267% -> 800 out of 300 rows.
Average Post-Fine-Tuning Similarity: 0.9213558


Query: Products for Color-blind people
 Similarity: 0.861:: Ethnic bias in health devices 'puts patients at risk'. The review focuses on devices frequently used in the NHS, like pulse oximeters and skin cancer apps.
 Similarity: 0.853:: 'I’ve invented an alternative to uncomfortable smear tests'. Sânziana Foia's non-invasive test detects harmful virus strains and delivers fast results at home.
 Similarity: 0.852:: Cost of living: How can I make extra income?. Some people have been earning thousands selling clothes and other items since they were in school.
 Similarity: 0.851:: What is behind the TikTok thirst for Stanley water cups?. People are camping outside supermarkets in the US to try to buy the latest internet on-trend item.
 Similarity: 0.850:: Farnham penguin finds 'guide bird' in one of her friends. Partially-sighted Squid the penguin, who developed cataracts as a chick, now has a guide to help.
 Similarity: 0.850:: Polling day is dehumanising, says blind voter. Elin Williams does not expect to be able to vote independently - like every election so far.
 Similarity: 0.850:: The explosions of colour that painted a Glasgow estate. Sony’s 2006 “Paint” advert is widely considered one of the most ambitious in history - but how was it made?
 Similarity: 0.849:: Top sunscreens fail protection tests, Which? says. Some cheaper lotions from supermarkets Aldi and Lidl outperformed more expensive brands, Which? said.
 Similarity: 0.849:: Nail technicians join forces to raise prices. Nail technicians unite to raise their charges in what they call "National Nail Price Increase Day”.
 Similarity: 0.849:: Where workers are exploited to harvest an everyday ingredient. Brazilian workers face degrading conditions to harvest palm wax used in sweets, pills and lipstick.


Query: JEEP off-road vehicles
 Similarity: 0.837:: How to drive in icy weather. Tips on what to carry in your car, and how to drive in snow and icy weather.
 Similarity: 0.829:: Our Range Rovers are not UK's most-stolen car, says Jaguar Land Rover. The boss of Jaguar Land Rover hits out at what he says is inaccurate reporting about the Range Rover.
 Similarity: 0.826:: California: Rockslide blocking road cleared with explosives. Video shared by Placer County shows a road completely blocked by boulders, that are then blasted into small pieces.
 Similarity: 0.825:: Watch: Wheelie bins fly and a caravan overturns in wind. Cars are damaged and houses shake as a suspected tornado strikes in Knutton, Staffordshire.
 Similarity: 0.825:: UAE: A hailstorm in the desert? Rare weather phenomenon shocks residents. Large hailstones covered roads as a rare weather phenomenon hit the United Arab Emirates.
 Similarity: 0.823:: TV star shaken after Jaguar brakes fail during drive. Craig Phillips describes "terrifying feeling" when brakes failed on his Jaguar I-Pace
 Similarity: 0.822:: Six skiers missing near Matterhorn in Swiss Alps. The Swiss Alps have seen high winds for some days, and over the last 24 hours, heavy snowfalls.
 Similarity: 0.822:: Collapsing cliffs and washed-out roads after California storms. Days of heavy rainfall in California have caused flooding and mudslides, leaving infrastructure damaged.
 Similarity: 0.822:: Ingenuity: Damage puts end to ground-breaking Mars helicopter mission. The first vehicle to achieve powered flight on another planet suffers rotor damage three years into tour.
 Similarity: 0.820:: Car slides on roof after drink-driver crash. Dashcam footage shows the car sliding along the carriageway with sparks flying out from underneath.


Query: What is the origin of Bamba snack
 Similarity: 0.850:: Big Zuu cuts down on cooking and rap for Ramadan. The rapper and TV chef visited Mecca for the first time to explore his Muslim faith for a documentary.
 Similarity: 0.846:: Scientists grow 'meaty' rice hybrid food for protein kick. A team in South Korea say they have cracked how to grow beef muscle and fat cells inside grains of rice.
 Similarity: 0.843:: What is behind the TikTok thirst for Stanley water cups?. People are camping outside supermarkets in the US to try to buy the latest internet on-trend item.
 Similarity: 0.842:: The Birmingham child who paved the way for the heel prick test. Sheila Jones, who had Phenylketonuria (PKU), was treated by pioneering doctors 70 years ago.
 Similarity: 0.842:: Giving babies smooth peanut butter could provide lifelong allergy defence. Risks of peanut allergy cut by 71% in teenagers who had peanut as a baby.
 Similarity: 0.840:: West Africa’s Michelin-starred cuisine wows London. African fine dining is often overlooked, but now restaurants are getting their just deserts.
 Similarity: 0.839:: Come Dine With Me winners part of drug import plot. Members of a gang to import cannabis were foiled after reports of a theft, police say.
 Similarity: 0.839:: Dorset family say they were 'shocked' at dog eating hairbands. Two-year-old Ham had a stomach full of hairbands that were removed by a Dorset vet.
 Similarity: 0.839:: Nigeria's love-hate relationship with twins. Two communities with different views about twins that meant the difference between life and death.
 Similarity: 0.838:: Raisin found in toddler's nose after three-month mystery. Three-year-old Peyton Handley told her parents that she had a pain and would scratch around her nose.


Query: Recommended diet and exercise habits for managing obesity
 Similarity: 0.896:: Weighing up diet drugs. Obesity jabs 'could reduce heart attack risk' says new study
 Similarity: 0.866:: Doctors question science behind blood sugar diet trend. Experts say there is "no strong evidence" the monitors, proven to be effective in managing diabetes, can also help people without the condition.
 Similarity: 0.862:: Katie Price low calorie diet advert banned. The social media post irresponsibly promoted a diet that fell below 800 calories a day, a watchdog says.
 Similarity: 0.862:: May horrified to learn about risks of diabetes disordered eating. Better awareness and more NHS support are needed, the former prime minister says.
 Similarity: 0.861:: Are we being tricked by our fitness trackers?. How accurate are fitness trackers?
 Similarity: 0.860:: Did bodybuilding bring on my early perimenopause?. Adele Johnston was 33 when she developed painful symptoms such as heart palpitations and itchy skin.
 Similarity: 0.860:: Why choosing whole grains can benefit our health. Why choosing whole grains can help your heart, your microbiome and your blood sugar.
 Similarity: 0.858:: Just five more ways Michael Mosley made us healthier. Michael Mosley’s simple and accessible health hacks made him a household name.  Remember these?
 Similarity: 0.858:: Rishi Sunak: Weekly fast is important discipline for me. The PM says fasting at the beginning of the week means he can "indulge" in sugary treats at other times.
 Similarity: 0.858:: Wegovy, the 'Viagra' of weight-loss drugs flying off the shelves. How did Danish weight-loss treatment Wegovy become a global sales sensation?


Query: Keep your children safe on the internet
 Similarity: 0.890:: Bereaved parents win online harm battle. Tech firms will have to hand over personal data of children whose death may be related to online harm.
 Similarity: 0.889:: Tame toxic algorithms to protect children, big tech told. Big tech companies will have to make changes to their algorithms to comply with new online safety laws.
 Similarity: 0.887:: Brianna Ghey's mother and Molly Russell's father join forces to combat online harm. Esther Ghey and Ian Russell want better protection for teenagers on social media.
 Similarity: 0.879:: Tech firms told to hide 'toxic' content from children. Social media firms like Instagram and TikTok will have to make changes to comply with new online safety laws.
 Similarity: 0.873:: Meta tool to block nude images in teens' private messages. The move is designed to help stop teenagers receiving inappropriate pictures, even in encrypted chats
 Similarity: 0.872:: Police investigate virtual sex assault on girl's avatar. The incident in a virtual world reportedly left the under-16-year-old traumatised.
 Similarity: 0.871:: Pupils get rare alert over dangers of sextortion. The National Crime Agency says young boys are increasingly being targeted by gangs.
 Similarity: 0.868:: Back-to-school illness advice offered to parents. Health officials explain when to keep your child at home and how to stop the spread of bugs.
 Similarity: 0.867:: New law aims to protect devices from hackers. Speakers, fitness trackers and other internet-connected devices sold in the UK now have to meet new requirements.
 Similarity: 0.866:: Rochdale abuse scandal: Inside the team fighting child sexual exploitation. How are police and child protection experts trying to prevent a repeat of the Rochdale abuse scandal?


Query: What are the lates news about AI ethics?
 Similarity: 0.892:: AI and humanity’s future: chilling or thrilling?. Amol & Nick take on Stephen Fry’s challenge & look at what the future of AI might entail.
 Similarity: 0.892:: Urgent need for terrorism AI laws, warns think tank. The government should 'urgently consider' AI-specific legislation a think-tank says.
 Similarity: 0.890:: Concern rises over AI in adult entertainment. AI in adult entertainment could have negative effects on society and individuals, experts say.
 Similarity: 0.890:: How AI is being used to prevent illegal fishing. Illegal fishing remains a huge global problem, but AI is now being used to tackle the issue.
 Similarity: 0.887:: CES 2024: AI pillows and toothbrushes - is it all getting a bit silly?. Companies are clamouring to present their products as AI-powered, but are their claims justified?
 Similarity: 0.887:: AI could 'supercharge' election disinformation, US tells the BBC. US Deputy Attorney General Lisa Monaco says the US wants tougher sentences for crimes involving AI.
 Similarity: 0.886:: How AI is helping to prevent future power cuts. Artificial intelligence software is being used to predict electricity demand and supply.
 Similarity: 0.886:: What happens when you think AI is lying about you?. BBC Tech Editor Zoe Kleinman tried to challenge the output of a chatbot - but all was not as it seemed.
 Similarity: 0.884:: New version of Chat-GPT can teach maths and flirt . OpenAI has unveiled a new, faster version of its generative AI tool, ChatGPT.
 Similarity: 0.884:: AI will not be the destroyer of jobs - Bank chief. Bank of England governor says AI has "great potential" as Lords report urges UK to embrace AI.


Query: How the war between Israel and Hamas is affecting global politics?
 Similarity: 0.911:: Chris Mason: How Gaza conflict is contorting UK politics. The Conservatives, Labour, and Parliament itself are finding themselves torn by the furious arguments provoked by the Israel-Gaza war.
 Similarity: 0.909:: Israel-Palestinian bitterness deepened by Hamas attack and war. Both Israelis and Palestinians believe the world does not understand their pain and suffering.
 Similarity: 0.902:: Could the Israel-Gaza war cost Biden the election?. The President’s said he’s 'outraged' by aid worker killings
 Similarity: 0.902:: Jeremy Bowen: What ICC arrest warrants mean for Israel and Hamas. The Israeli and Hamas leaders are suspected of committing war crimes during the continuing war in Gaza.
 Similarity: 0.900:: No let-up for Gazans while world focused on Iran attacks. Fighting continues in Gaza, where a humanitarian crisis is overshadowed by the wider regional conflict.
 Similarity: 0.900:: Have Iran-Israel missile strikes changed the Middle East?. Political and military leaders are still absorbing the extraordinary exchange of fire, writes James Landale.
 Similarity: 0.899:: Israel-Gaza war: Latest ceasefire talks not very promising - Qatar. Israel's PM Benjamin Netanyahu vows to carry on the war against Hamas regardless of international pressure.
 Similarity: 0.897:: Why have Israel and Iran attacked each other?. The long-running shadow war between the two countries has come into the open.
 Similarity: 0.897:: How plans for ‘the day after’ could help end war in Gaza. This subject will be on the table when EU and Middle Eastern foreign ministers meet.
 Similarity: 0.896:: Lyse Doucet: Hamas leader's assassination sparks wider war fears. Lyse Doucet assesses if Hezbollah and Hamas will retaliate after Saleh al-Arouri was killed in Lebanon.


Query: Latest trends in the fashion industry
 Similarity: 0.879:: How Zendaya perfected 'method dressing'. Film stars have made fancy dress fashionable in their recent red carpet looks.
 Similarity: 0.874:: Champagne, caffeine and chaos: Fashion week descends on Paris. Louis Vuitton, Dior, Hermes, Rick Owens, Loewe, Kenzo and Dries Van Noten all introduce new collections in Paris.
 Similarity: 0.866:: In pictures:  Daisy's hot pants and other striking outfits from the red carpet. Big names from films like Barbie, Oppenheimer and Saltburn step out at the British awards ceremony.
 Similarity: 0.864:: The most eye-catching looks from the Met Gala so far. Lea Michelle, Zendaya and Gigi Hadid are among the stars walking the red carpet.
 Similarity: 0.864:: Stars take over Paris for sporty Vogue fashion show. Supermodels, singers and sports star took to the runway in Paris as Vogue turned a square into a runway.
 Similarity: 0.861:: Zendaya and Kim Kardashian stun on Met Gala red carpet. The celebrities are showing up for fashion's night of nights in New York City.
 Similarity: 0.861:: Kuenssberg: Are the politics of climate change going out of fashion?. Debate is shifting to cost concerns as net zero targets fast approach, says Laura Kuenssberg.
 Similarity: 0.859:: ‘Insane’ journey for NI supermodel from grammar school to Dior. Omagh teenager Alice McGrath is the latest face of high fashion after being discovered online.
 Similarity: 0.859:: Vinted makes first profit on used fashion. The second-hand fashion marketplace is the first of the new "pre-loved" clothing platforms to make a profit.
 Similarity: 0.859:: Victoria Beckham's fashion show disrupted by Peta. The 49-year-old Spice Girl was showcasing her label's autumn/winter collection at Paris Fashion Week.


Query: Interest rates
 Similarity: 0.904:: Interest rates expected to be held at 5.25%. Despite inflation falling to 2%, experts are expecting interest rates to be held at a 16-year high.
 Similarity: 0.896:: What are UK interest rates and when will they fall?. Bank of England interest rates affect the mortgage, loan and savings rates for millions of people.
 Similarity: 0.895:: How do interest rates affect me?. Bank of England interest rates have an impact on the mortgage, loan and savings rates for millions of people.
 Similarity: 0.895:: When will UK interest rates come down?. Bank of England interest rates affect mortgage, loan and savings rates for millions of people.
 Similarity: 0.894:: Interest rate cuts 'on the way', says Bank boss. The Bank of England has kept the cost of borrowing at 5.25% for the fifth time in a row.
 Similarity: 0.892:: Bank of England expected to hold interest rates. The Bank is widely expected to keep rates at 5.25% for now, but cut them later in the year.
 Similarity: 0.891:: Inflation and Covid set our savings back 10 years. Justin Williams is one of many whose savings have eroded and mortgage rates have increased.
 Similarity: 0.891:: Mortgage lenders rapidly changing interest rates. HSBC, NatWest and Virgin Money are all increasing mortgage rates continuing a frantic start to the year.
 Similarity: 0.888:: Bank 'optimistic' as it edges closer to summer cut. Its comments came as UK interest rates were left unchanged at a 16-year high of 5.25%.
 Similarity: 0.884:: Interest rates won't fall due to 4% inflation, says Bank boss. Bank of England boss says the latest inflation figure "pretty much leaves us where we were".


Query: biden vs trump
 Similarity: 0.908:: Super Tuesday: Everything Points to Trump vs Biden. Trump and Biden win almost every state in election season's biggest primary night.
 Similarity: 0.907:: Where Biden and Trump stand on key issues. How the two candidates' policies compare on the economy, immigration, abortion and other big issues.
 Similarity: 0.906:: What to watch for at Biden and Trump's first debate. The BBC's Sarah Smith looks at what's at stake for both men as they prove they're worth a second White House term.
 Similarity: 0.906:: Illegal migration, tax and abortion - fact checking Trump-Biden debate. BBC Verify looks into various claims made on stage by Donald Trump and Joe Biden.
 Similarity: 0.906:: Big stakes and high tension as Biden-Trump debate looms. Thursday's debate between the two will be a reunion of sorts - although not exactly a friendly one.
 Similarity: 0.902:: Biden and Trump make competing trips to US border. The two likely presidential candidates make speeches in an effort to show they can tackle illegal crossings.
 Similarity: 0.900:: Watch key moments from Biden and Trump's first debate. The pair threw insults and clashed on stage about the biggest issues American voters care about - here's what they said.
 Similarity: 0.899:: 'A reality show': World reacts to Trump-Biden debate . Global reviews were most scathing of Mr Biden, but his Republican challenger did not escape criticism.
 Similarity: 0.898:: Biden faces high-stakes address to calm Democratic nerves. The president will seek to fight concerns over his age and contrast his term in office with Donald Trump's.
 Similarity: 0.897:: Biden and Trump agree two debates as RFK cries foul. There will be no live audience at June's Atlanta event, which will mark the pair's first on-stage clash in four years.


Query: Best Marvel movie this year
 Similarity: 0.859:: Marvel star Jeremy Renner: I'm so blessed a year after accident. The Marvel star reflects on his recovery after being run over by his own snow plough last New Year's Day.
 Similarity: 0.850:: Oscars 2024: Poor Things and Anatomy of a Fall scoop early awards. Best picture favourite Oppenheimer has 13 nominations and could become one of the biggest winners of all time.
 Similarity: 0.848:: Tom Holland's Romeo wows crowds more than critics. Reviews describe the Spider-Man star's performance on stage as "good", "fine" and "perfectly OK".
 Similarity: 0.846:: Oppenheimer's Cillian Murphy and Robert Downey Jr scoop Bafta Film Awards. Cillian Murphy, Robert Downey Jr and Christopher Nolan all win Bafta Film Awards for Oppenheimer.
 Similarity: 0.845:: Marvel star Karen Gillan is not scared of being cancelled . Scots actress Karen Gillan's new role made her face up to the pitfalls of social media.
 Similarity: 0.843:: Oppenheimer among Bafta best film nominees. Barbie was the top grossing film of 2023 and received great reviews, but missed out on a best film nomination.
 Similarity: 0.843:: Bafta nominations 2024: The full list of film contenders. Oppenheimer and Poor Things are the leading contenders for this year's British Academy Film Awards.
 Similarity: 0.843:: Oppenheimer: Cillian Murphy film marches towards Oscars success. Christopher Nolan's film got another boost in its awards campaign at last week's Golden Globes.
 Similarity: 0.841:: The Oppenheimer story that won't win Oscars. The film shines a light on the work done by scientists in New Mexico but locals say their story is untold.
 Similarity: 0.841:: Oscars 2024: Everything you need to know ahead of big night of awards. As Hollywood's finest get ready for the big night, we bring you the lowdown on what to look out for.


Query: Northern Lights

# 1K queries, Rank 4, alpha 4

In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split

from pymongo import MongoClient
import pandas as pd

# MongoDB connection details
mongo_uri = "mongodb://localhost:27017/"
db_name = "task1"
collection_name = "bbc_news"

# Connect to MongoDB
client = MongoClient(mongo_uri)
db = client[db_name]
collection = db[collection_name]

documents = list(collection.find())
df = pd.DataFrame(documents)
client.close()

queries_df = pd.read_csv('notebooks_data/generated_queries.csv')
queries_df = queries_df.iloc[:1000]

train_df, test_df = train_test_split(queries_df, test_size=0.3, random_state=42)
print(f"Training set size: {len(train_df)}")
print(f"Test set size: {len(test_df)}")

from transformers import AutoTokenizer, AutoModel
from peft import LoraConfig, get_peft_model

# Load tokenizer and model without quantization
model_name = "intfloat/e5-large-v2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)  # Standard loading, no quantization

# Define QLoRA configuration
lora_config = LoraConfig(
    r=4,               # Rank of the low-rank matrices
    lora_alpha=4,      # Scaling factor for LoRA updates
    target_modules=["key", "query", "value"],  # Adjust based on model structure if necessary
    lora_dropout=0.1,   # Dropout for LoRA layers
    bias="none"         # Exclude biases to focus on core layers
)

# Wrap the model with QLoRA
model = get_peft_model(model, lora_config)

Training set size: 700
Test set size: 300

In [21]:
import torch

def get_embeddings(text, model, tokenizer):
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True).to("cpu")
    with torch.no_grad():
        embeddings = model(**inputs).last_hidden_state.mean(dim=1).cpu().numpy()
    return embeddings


from sklearn.metrics.pairwise import cosine_similarity

def find_top_news(query, df, model, tokenizer, top_k=10):
    query_embedding = get_embeddings(query, model, tokenizer)

    # Calculate cosine similarity between query and all news embeddings
    similarities = df['e5_embedding_before_tuning'].apply(lambda x: cosine_similarity(query_embedding, x)[0][0])
    
    # Add similarity scores to the DataFrame
    df['e5_similarity'] = similarities
    
    # Sort by similarity and return the top_k results
    top_matches = df.nlargest(top_k, 'e5_similarity')
    
    # Clean up by dropping the 'similarity' column
    df.drop(columns=['e5_similarity'], inplace=True)
    
    return top_matches[['content', 'e5_similarity']]

In [22]:
from torch.utils.data import Dataset, DataLoader

class QueryNewsDataset(Dataset):
    def __init__(self, df, tokenizer, max_length=128):
        self.queries = df['query'].tolist()
        self.news = df['news_content'].tolist()
        self.tokenizer = tokenizer
        self.max_length = max_length
    
    def __len__(self):
        return len(self.queries)
    
    def __getitem__(self, idx):
        query_text = self.queries[idx]
        news_text = self.news[idx]
        
        query_inputs = self.tokenizer(query_text, padding='max_length', truncation=True, max_length=self.max_length, return_tensors="pt")
        news_inputs = self.tokenizer(news_text, padding='max_length', truncation=True, max_length=self.max_length, return_tensors="pt")
        
        return {
            'query_input_ids': query_inputs['input_ids'].squeeze(0),
            'query_attention_mask': query_inputs['attention_mask'].squeeze(0),
            'news_input_ids': news_inputs['input_ids'].squeeze(0),
            'news_attention_mask': news_inputs['attention_mask'].squeeze(0)
        }

# Create DataLoader for fine-tuning
train_loader = DataLoader(QueryNewsDataset(test_df, tokenizer), batch_size=8, shuffle=True)




import torch
from torch.nn import functional as F
from transformers import AdamW

# Optimizer
optimizer = AdamW(model.parameters(), lr=2e-5)

# Custom similarity loss function
def similarity_loss(embedding1, embedding2):
    cos_sim = F.cosine_similarity(embedding1, embedding2)
    return 1 - cos_sim.mean()

# Fine-tuning loop with progress updates
model.train()
for epoch in range(3):  # Adjust the number of epochs as needed
    total_loss = 0
    for i, batch in enumerate(train_loader):
        optimizer.zero_grad()
        
        # Query embeddings
        query_embeddings = model(
            input_ids=batch['query_input_ids'],
            attention_mask=batch['query_attention_mask']
        ).last_hidden_state.mean(dim=1)
        
        # News content embeddings
        news_embeddings = model(
            input_ids=batch['news_input_ids'],
            attention_mask=batch['news_attention_mask']
        ).last_hidden_state.mean(dim=1)
        
        # Calculate similarity loss and optimize
        loss = similarity_loss(query_embeddings, news_embeddings)
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
        
        # Print progress within each epoch
        if (i + 1) % 10 == 0:
            percent_complete = ((i + 1) / len(train_loader)) * 100
            print(f"Epoch {epoch + 1} - Processed {percent_complete:.0f}% -> {i + 1} out of {len(train_loader)} batches.")

    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch + 1} completed with average loss: {avg_loss:.4f}")

/Users/who/projects/task1/venv/lib/python3.11/site-packages/transformers/optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(

Epoch 1 - Processed 26% -> 10 out of 38 batches.
Epoch 1 - Processed 53% -> 20 out of 38 batches.
Epoch 1 - Processed 79% -> 30 out of 38 batches.
Epoch 1 completed with average loss: 0.1381
Epoch 2 - Processed 26% -> 10 out of 38 batches.
Epoch 2 - Processed 53% -> 20 out of 38 batches.
Epoch 2 - Processed 79% -> 30 out of 38 batches.
Epoch 2 completed with average loss: 0.1339
Epoch 3 - Processed 26% -> 10 out of 38 batches.
Epoch 3 - Processed 53% -> 20 out of 38 batches.
Epoch 3 - Processed 79% -> 30 out of 38 batches.
Epoch 3 completed with average loss: 0.1261

In [23]:
# Post-fine-tuning similarity calculation with progress updates
similarities_after = []
model.eval()
for i, row in test_df.iterrows():
    query_embedding = get_embeddings(row['query'], model, tokenizer)
    content_embedding = get_embeddings(row['news_content'], model, tokenizer)
    similarity = cosine_similarity(query_embedding, content_embedding)[0][0]
    similarities_after.append(similarity)
    
    # Print progress
    if (i + 1) % 100 == 0:
        percent_complete = ((i + 1) / len(test_df)) * 100
        print(f"Processed {percent_complete:.0f}% -> {i + 1} out of {len(test_df)} rows.")

print("Average Post-Fine-Tuning Similarity:", sum(similarities_after) / len(similarities_after))

df['e5_embedding_before_tuning'] = df['content'].apply(lambda x: get_embeddings(x, model, tokenizer))

test_queries = ["Products for Color-blind people","JEEP off-road vehicles","What is the origin of Bamba snack","Recommended diet and exercise habits for managing obesity","Keep your children safe on the internet","What are the lates news about AI ethics?","How the war between Israel and Hamas is affecting global politics?","Latest trends in the fashion industry","Interest rates","biden vs trump","Best Marvel movie this year","Northern Lights"]
for user_query in test_queries:
    print(f"\n\nQuery: {user_query}")
    top_news = find_top_news(user_query, df, model, tokenizer)
    for _, row in top_news.iterrows():
                print(f"\033[96m Similarity: {row['e5_similarity']:.3f}::\033[0m {row['content']}")

Processed 300% -> 900 out of 300 rows.
Processed 167% -> 500 out of 300 rows.
Processed 100% -> 300 out of 300 rows.
Processed 200% -> 600 out of 300 rows.
Processed 67% -> 200 out of 300 rows.
Processed 267% -> 800 out of 300 rows.
Average Post-Fine-Tuning Similarity: 0.8682825


Query: Products for Color-blind people
 Similarity: 0.799:: Cost of living: How can I make extra income?. Some people have been earning thousands selling clothes and other items since they were in school.
 Similarity: 0.799:: Ethnic bias in health devices 'puts patients at risk'. The review focuses on devices frequently used in the NHS, like pulse oximeters and skin cancer apps.
 Similarity: 0.790:: 'I’ve invented an alternative to uncomfortable smear tests'. Sânziana Foia's non-invasive test detects harmful virus strains and delivers fast results at home.
 Similarity: 0.789:: Electioncast: Laura Kuenssberg and Adam Fleming answer your questions. Adam and Laura answer your election questions
 Similarity: 0.789:: Aphantasia: Why I cannot see my children in my mind. Not everyone can picture images in their mind's eye and remember sounds or faces - but why?
 Similarity: 0.788:: Americanswers! What is Project 2025? Will Biden take a cognitive test?. We answer your questions on the biggest issues in the run-up to the election
 Similarity: 0.788:: Who can I vote for in the general election?. Find out which constituency you are in, who you can vote for and where you can vote using our postcode search.
 Similarity: 0.787:: The List. Exploring 9 amazing space missions.
 Similarity: 0.787:: Warning over children using anti-ageing skincare products. Dermatologists say products with ingredients potentially harmful to children are growing popular.
 Similarity: 0.787:: Cost of living payments: What are they and who gets them?. Millions of low-income households will receive a final cost of living payment soon.


Query: JEEP off-road vehicles
 Similarity: 0.780:: How to drive in icy weather. Tips on what to carry in your car, and how to drive in snow and icy weather.
 Similarity: 0.759:: Watch: Wheelie bins fly and a caravan overturns in wind. Cars are damaged and houses shake as a suspected tornado strikes in Knutton, Staffordshire.
 Similarity: 0.759:: Our Range Rovers are not UK's most-stolen car, says Jaguar Land Rover. The boss of Jaguar Land Rover hits out at what he says is inaccurate reporting about the Range Rover.
 Similarity: 0.758:: Collapsing cliffs and washed-out roads after California storms. Days of heavy rainfall in California have caused flooding and mudslides, leaving infrastructure damaged.
 Similarity: 0.758:: TV star shaken after Jaguar brakes fail during drive. Craig Phillips describes "terrifying feeling" when brakes failed on his Jaguar I-Pace
 Similarity: 0.756:: Adults and teens turn to 'dumbphones'  to cut screen time. Parents and teens alike are trading in their smartphones for "dumber" models to help stay offline.
 Similarity: 0.756:: California: Rockslide blocking road cleared with explosives. Video shared by Placer County shows a road completely blocked by boulders, that are then blasted into small pieces.
 Similarity: 0.755:: UAE: A hailstorm in the desert? Rare weather phenomenon shocks residents. Large hailstones covered roads as a rare weather phenomenon hit the United Arab Emirates.
 Similarity: 0.753:: Have the wheels come off for Tesla?. As the electric carmaker sees sales fall and cuts jobs, we take a closer look at its problems.
 Similarity: 0.752:: Israeli army strapped wounded Palestinian to jeep in West Bank. The Israeli military says the man was a suspect in a raid in the West Bank, but its forces violated protocol.


Query: What is the origin of Bamba snack
 Similarity: 0.777:: Big Zuu cuts down on cooking and rap for Ramadan. The rapper and TV chef visited Mecca for the first time to explore his Muslim faith for a documentary.
 Similarity: 0.776:: The Birmingham child who paved the way for the heel prick test. Sheila Jones, who had Phenylketonuria (PKU), was treated by pioneering doctors 70 years ago.
 Similarity: 0.776:: Scientists grow 'meaty' rice hybrid food for protein kick. A team in South Korea say they have cracked how to grow beef muscle and fat cells inside grains of rice.
 Similarity: 0.773:: Nigeria's love-hate relationship with twins. Two communities with different views about twins that meant the difference between life and death.
 Similarity: 0.773:: Kamila Valieva claimed contaminated strawberry dessert behind positive test. Banned figure skater Kamila Valieva claimed her positive doping test may have been caused by a contaminated strawberry dessert.
 Similarity: 0.772:: Come Dine With Me winners part of drug import plot. Members of a gang to import cannabis were foiled after reports of a theft, police say.
 Similarity: 0.771:: Raisin found in toddler's nose after three-month mystery. Three-year-old Peyton Handley told her parents that she had a pain and would scratch around her nose.
 Similarity: 0.770:: One Love: How Kingsley Ben-Adir became Bob Marley on the set of Barbie. The actor initially turned down the role, saying it was too risky. What changed his mind?
 Similarity: 0.770:: What is behind the TikTok thirst for Stanley water cups?. People are camping outside supermarkets in the US to try to buy the latest internet on-trend item.
 Similarity: 0.770:: Two brothers, one club and a 40-year wait. Inaki and Nico Williams' parents travelled to Bilbao from Ghana hoping the city would change their sons' lives. Their sons, in turn, have changed the city.


Query: Recommended diet and exercise habits for managing obesity
 Similarity: 0.843:: Weighing up diet drugs. Obesity jabs 'could reduce heart attack risk' says new study
 Similarity: 0.809:: How do I register to vote?. Here’s what you need to know about how you register to vote and when.
 Similarity: 0.809:: Are we being tricked by our fitness trackers?. How accurate are fitness trackers?
 Similarity: 0.803:: Post Christmas debt: Which bills should I pay first?. What help and options are available to people struggling with debt repayments?
 Similarity: 0.802:: How to drive in icy weather. Tips on what to carry in your car, and how to drive in snow and icy weather.
 Similarity: 0.799:: Doctors question science behind blood sugar diet trend. Experts say there is "no strong evidence" the monitors, proven to be effective in managing diabetes, can also help people without the condition.
 Similarity: 0.798:: What can I do if I can't pay my energy bill?. If you're struggling to afford your gas and electricity bills, what options are available?
 Similarity: 0.798:: Why fat Labradors can blame their genes. Scientists used the 'sausage in a box' test to find out that dogs can be a "hard-wired" for obesity.
 Similarity: 0.798:: How to win an Oscar. The campaigning behind the Academy Awards
 Similarity: 0.796:: Dog attacks: What can you do to protect yourself?. The best course of action will vary depending on the situation, dog behaviour experts explain.


Query: Keep your children safe on the internet
 Similarity: 0.835:: Tame toxic algorithms to protect children, big tech told. Big tech companies will have to make changes to their algorithms to comply with new online safety laws.
 Similarity: 0.832:: Bereaved parents win online harm battle. Tech firms will have to hand over personal data of children whose death may be related to online harm.
 Similarity: 0.832:: Brianna Ghey's mother and Molly Russell's father join forces to combat online harm. Esther Ghey and Ian Russell want better protection for teenagers on social media.
 Similarity: 0.822:: Tech firms told to hide 'toxic' content from children. Social media firms like Instagram and TikTok will have to make changes to comply with new online safety laws.
 Similarity: 0.815:: Back-to-school illness advice offered to parents. Health officials explain when to keep your child at home and how to stop the spread of bugs.
 Similarity: 0.813:: Rochdale abuse scandal: Inside the team fighting child sexual exploitation. How are police and child protection experts trying to prevent a repeat of the Rochdale abuse scandal?
 Similarity: 0.811:: Meta tool to block nude images in teens' private messages. The move is designed to help stop teenagers receiving inappropriate pictures, even in encrypted chats
 Similarity: 0.810:: Police investigate virtual sex assault on girl's avatar. The incident in a virtual world reportedly left the under-16-year-old traumatised.
 Similarity: 0.807:: New law aims to protect devices from hackers. Speakers, fitness trackers and other internet-connected devices sold in the UK now have to meet new requirements.
 Similarity: 0.806:: Pupils get rare alert over dangers of sextortion. The National Crime Agency says young boys are increasingly being targeted by gangs.


Query: What are the lates news about AI ethics?
 Similarity: 0.826:: AI and humanity’s future: chilling or thrilling?. Amol & Nick take on Stephen Fry’s challenge & look at what the future of AI might entail.
 Similarity: 0.825:: How AI is being used to prevent illegal fishing. Illegal fishing remains a huge global problem, but AI is now being used to tackle the issue.
 Similarity: 0.825:: Concern rises over AI in adult entertainment. AI in adult entertainment could have negative effects on society and individuals, experts say.
 Similarity: 0.824:: CES 2024: AI pillows and toothbrushes - is it all getting a bit silly?. Companies are clamouring to present their products as AI-powered, but are their claims justified?
 Similarity: 0.822:: New version of Chat-GPT can teach maths and flirt . OpenAI has unveiled a new, faster version of its generative AI tool, ChatGPT.
 Similarity: 0.821:: Urgent need for terrorism AI laws, warns think tank. The government should 'urgently consider' AI-specific legislation a think-tank says.
 Similarity: 0.821:: How AI is helping to prevent future power cuts. Artificial intelligence software is being used to predict electricity demand and supply.
 Similarity: 0.820:: AI could 'supercharge' election disinformation, US tells the BBC. US Deputy Attorney General Lisa Monaco says the US wants tougher sentences for crimes involving AI.
 Similarity: 0.818:: AI will not be the destroyer of jobs - Bank chief. Bank of England governor says AI has "great potential" as Lords report urges UK to embrace AI.
 Similarity: 0.817:: What happens when you think AI is lying about you?. BBC Tech Editor Zoe Kleinman tried to challenge the output of a chatbot - but all was not as it seemed.


Query: How the war between Israel and Hamas is affecting global politics?
 Similarity: 0.856:: Israel-Palestinian bitterness deepened by Hamas attack and war. Both Israelis and Palestinians believe the world does not understand their pain and suffering.
 Similarity: 0.853:: Chris Mason: How Gaza conflict is contorting UK politics. The Conservatives, Labour, and Parliament itself are finding themselves torn by the furious arguments provoked by the Israel-Gaza war.
 Similarity: 0.848:: Could the Israel-Gaza war cost Biden the election?. The President’s said he’s 'outraged' by aid worker killings
 Similarity: 0.846:: Jeremy Bowen: What ICC arrest warrants mean for Israel and Hamas. The Israeli and Hamas leaders are suspected of committing war crimes during the continuing war in Gaza.
 Similarity: 0.838:: No let-up for Gazans while world focused on Iran attacks. Fighting continues in Gaza, where a humanitarian crisis is overshadowed by the wider regional conflict.
 Similarity: 0.837:: Israel-Gaza war: Latest ceasefire talks not very promising - Qatar. Israel's PM Benjamin Netanyahu vows to carry on the war against Hamas regardless of international pressure.
 Similarity: 0.837:: Jeremy Bowen: Obstacles to peace seem larger than ever. The risk of an all-out Middle East war is increasing as the crisis in Gaza grows ever more desperate.
 Similarity: 0.837:: Why have Israel and Iran attacked each other?. The long-running shadow war between the two countries has come into the open.
 Similarity: 0.837:: Lyse Doucet: Hamas leader's assassination sparks wider war fears. Lyse Doucet assesses if Hezbollah and Hamas will retaliate after Saleh al-Arouri was killed in Lebanon.
 Similarity: 0.837:: Have Iran-Israel missile strikes changed the Middle East?. Political and military leaders are still absorbing the extraordinary exchange of fire, writes James Landale.


Query: Latest trends in the fashion industry
 Similarity: 0.821:: How Zendaya perfected 'method dressing'. Film stars have made fancy dress fashionable in their recent red carpet looks.
 Similarity: 0.810:: Champagne, caffeine and chaos: Fashion week descends on Paris. Louis Vuitton, Dior, Hermes, Rick Owens, Loewe, Kenzo and Dries Van Noten all introduce new collections in Paris.
 Similarity: 0.804:: Egg Freezing and Me. Inside the world of one of the fastest growing fertility treatments in the UK.
 Similarity: 0.801:: The new language changing the dating scene. If you WLTM a ND with a GSOH, you might struggle to locate one on a modern dating app.
 Similarity: 0.801:: Kuenssberg: Are the politics of climate change going out of fashion?. Debate is shifting to cost concerns as net zero targets fast approach, says Laura Kuenssberg.
 Similarity: 0.798:: Stars take over Paris for sporty Vogue fashion show. Supermodels, singers and sports star took to the runway in Paris as Vogue turned a square into a runway.
 Similarity: 0.798:: Cambodia: Fast fashion helps fuel blazing kilns where workers faint from heat. How hot is too hot to work? The BBC visits Cambodia's sweltering brick kilns to find out.
 Similarity: 0.798:: The most eye-catching looks from the Met Gala so far. Lea Michelle, Zendaya and Gigi Hadid are among the stars walking the red carpet.
 Similarity: 0.798:: Zendaya and Kim Kardashian stun on Met Gala red carpet. The celebrities are showing up for fashion's night of nights in New York City.
 Similarity: 0.797:: In pictures:  Daisy's hot pants and other striking outfits from the red carpet. Big names from films like Barbie, Oppenheimer and Saltburn step out at the British awards ceremony.


Query: Interest rates
 Similarity: 0.851:: Interest rates expected to be held at 5.25%. Despite inflation falling to 2%, experts are expecting interest rates to be held at a 16-year high.
 Similarity: 0.849:: What are UK interest rates and when will they fall?. Bank of England interest rates affect the mortgage, loan and savings rates for millions of people.
 Similarity: 0.847:: How do interest rates affect me?. Bank of England interest rates have an impact on the mortgage, loan and savings rates for millions of people.
 Similarity: 0.845:: Inflation and Covid set our savings back 10 years. Justin Williams is one of many whose savings have eroded and mortgage rates have increased.
 Similarity: 0.845:: When will UK interest rates come down?. Bank of England interest rates affect mortgage, loan and savings rates for millions of people.
 Similarity: 0.840:: Mortgage lenders rapidly changing interest rates. HSBC, NatWest and Virgin Money are all increasing mortgage rates continuing a frantic start to the year.
 Similarity: 0.839:: Interest rate cuts 'on the way', says Bank boss. The Bank of England has kept the cost of borrowing at 5.25% for the fifth time in a row.
 Similarity: 0.839:: Bank of England expected to hold interest rates. The Bank is widely expected to keep rates at 5.25% for now, but cut them later in the year.
 Similarity: 0.834:: Interest rates won't fall due to 4% inflation, says Bank boss. Bank of England boss says the latest inflation figure "pretty much leaves us where we were".
 Similarity: 0.833:: Bank 'optimistic' as it edges closer to summer cut. Its comments came as UK interest rates were left unchanged at a 16-year high of 5.25%.


Query: biden vs trump
 Similarity: 0.867:: Super Tuesday: Everything Points to Trump vs Biden. Trump and Biden win almost every state in election season's biggest primary night.
 Similarity: 0.864:: Where Biden and Trump stand on key issues. How the two candidates' policies compare on the economy, immigration, abortion and other big issues.
 Similarity: 0.862:: Illegal migration, tax and abortion - fact checking Trump-Biden debate. BBC Verify looks into various claims made on stage by Donald Trump and Joe Biden.
 Similarity: 0.859:: What to watch for at Biden and Trump's first debate. The BBC's Sarah Smith looks at what's at stake for both men as they prove they're worth a second White House term.
 Similarity: 0.858:: Watch key moments from Biden and Trump's first debate. The pair threw insults and clashed on stage about the biggest issues American voters care about - here's what they said.
 Similarity: 0.856:: Big stakes and high tension as Biden-Trump debate looms. Thursday's debate between the two will be a reunion of sorts - although not exactly a friendly one.
 Similarity: 0.856:: Biden faces high-stakes address to calm Democratic nerves. The president will seek to fight concerns over his age and contrast his term in office with Donald Trump's.
 Similarity: 0.855:: Biden and Trump make competing trips to US border. The two likely presidential candidates make speeches in an effort to show they can tackle illegal crossings.
 Similarity: 0.849:: 'A reality show': World reacts to Trump-Biden debate . Global reviews were most scathing of Mr Biden, but his Republican challenger did not escape criticism.
 Similarity: 0.849:: Biden and Trump agree two debates as RFK cries foul. There will be no live audience at June's Atlanta event, which will mark the pair's first on-stage clash in four years.


Query: Best Marvel movie this year
 Similarity: 0.807:: Marvel star Jeremy Renner: I'm so blessed a year after accident. The Marvel star reflects on his recovery after being run over by his own snow plough last New Year's Day.
 Similarity: 0.790:: Oscars 2024: Poor Things and Anatomy of a Fall scoop early awards. Best picture favourite Oppenheimer has 13 nominations and could become one of the biggest winners of all time.
 Similarity: 0.789:: Tom Holland's Romeo wows crowds more than critics. Reviews describe the Spider-Man star's performance on stage as "good", "fine" and "perfectly OK".
 Similarity: 0.787:: Marvel star Karen Gillan is not scared of being cancelled . Scots actress Karen Gillan's new role made her face up to the pitfalls of social media.
 Similarity: 0.787:: Oppenheimer's Cillian Murphy and Robert Downey Jr scoop Bafta Film Awards. Cillian Murphy, Robert Downey Jr and Christopher Nolan all win Bafta Film Awards for Oppenheimer.
 Similarity: 0.784:: Bafta nominations 2024: The full list of film contenders. Oppenheimer and Poor Things are the leading contenders for this year's British Academy Film Awards.
 Similarity: 0.784:: Oscars 2024: Everything you need to know ahead of big night of awards. As Hollywood's finest get ready for the big night, we bring you the lowdown on what to look out for.
 Similarity: 0.782:: 'The Valhalla nail-biter that had everything'. Xander Schauffele’s thrilling breakthrough PGA victory over Bryson DeChambeau portrayed major golf in the best possible light, writes Iain Carter.
 Similarity: 0.781:: The full list of Oscar winners - updating live. See who has won and been nominated for this year's coveted Academy Awards.
 Similarity: 0.781:: The Oppenheimer story that won't win Oscars. The film shines a light on the work done by scientists in New Mexico but locals say their story is untold.


Query: Northern Lights
 Similarity: 0.865:: Why you probably missed the Northern Lights on Saturday. The Northern Lights waned early on Saturday night, but picked up again much later.
 Similarity: 0.864:: More Northern Lights soon as Sun storms strengthen. Another spectacular light show could come within two weeks as Sun storms reach 11-year high.